/**
 * Phase 2A relational schema (DESIGN-approved, implemented here).
 *
 * Clean-reset model: the single JSON `school_documents` blob is no longer the
 * application data architecture. All school data lives in these tables.
 *
 * The legacy `/api/school` + `school_documents` path remains only as a
 * temporary backward-compat shim for the current frontend; it will be removed
 * once the workspaces become pure API consumers (implementation step 16).
 *
 * Conventions:
 * - TEXT primary keys generated by `uid(...)` (matches existing app code).
 * - snake_case columns, TEXT ISO-8601 timestamps/dates (matches existing rows).
 * - branch membership sourced from assignment tables — users carry NO branch.
 */

export const SCHEMA_SQL = `
-- =====================================================================
-- Lookups
-- =====================================================================

CREATE TABLE IF NOT EXISTS duties (
  code TEXT PRIMARY KEY,
  label_ar TEXT NOT NULL,
  label_fr TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS assessment_types (
  code TEXT PRIMARY KEY,
  label_ar TEXT NOT NULL,
  label_fr TEXT NOT NULL,
  weight NUMERIC(6,2) NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0
);

-- =====================================================================
-- Identity & sessions (existing)
-- =====================================================================

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'staff',
  password_hash TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  staff_id TEXT,
  student_id TEXT,
  duties TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);

-- =====================================================================
-- Organization: branches + organizational authorities
-- =====================================================================

CREATE TABLE IF NOT EXISTS branches (
  id TEXT PRIMARY KEY,
  name_ar TEXT NOT NULL UNIQUE,
  name_fr TEXT NOT NULL DEFAULT '',
  name_en TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT true,
  is_default BOOLEAN NOT NULL DEFAULT false,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- One active Branch Head per branch AND one active branch per Branch Head.
CREATE TABLE IF NOT EXISTS branch_heads (
  id TEXT PRIMARY KEY,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  active BOOLEAN NOT NULL DEFAULT true,
  appointed_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  appointed_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_branch_heads_active_branch ON branch_heads(branch_id) WHERE active = true;
CREATE UNIQUE INDEX IF NOT EXISTS idx_branch_heads_active_user ON branch_heads(user_id) WHERE active = true;

-- PK(branch_id) => exactly one (primary) Financial Officer per branch.
-- Same officer in multiple rows => one FO covering multiple branches.
CREATE TABLE IF NOT EXISTS branch_financial_officers (
  branch_id TEXT PRIMARY KEY REFERENCES branches(id) ON DELETE CASCADE,
  financial_officer_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'active',
  assigned_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  assigned_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_fo_user ON branch_financial_officers(financial_officer_user_id);

-- =====================================================================
-- Assignments: branch membership + operational responsibilities
-- =====================================================================

-- Employee branch membership (1 row today, schema supports many later).
CREATE TABLE IF NOT EXISTS user_branch_assignments (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  assigned_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  assigned_at TEXT NOT NULL,
  UNIQUE (user_id, branch_id)
);
CREATE INDEX IF NOT EXISTS idx_user_branch_assignments_branch ON user_branch_assignments(branch_id);

-- Operational duties per branch (delegation surface). Never central duties.
CREATE TABLE IF NOT EXISTS branch_responsibilities (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  duty_code TEXT NOT NULL REFERENCES duties(code),
  assigned_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  assigned_at TEXT NOT NULL,
  UNIQUE (user_id, branch_id, duty_code)
);
CREATE INDEX IF NOT EXISTS idx_branch_responsibilities_branch ON branch_responsibilities(branch_id);
CREATE INDEX IF NOT EXISTS idx_branch_responsibilities_user ON branch_responsibilities(user_id);

-- Teachers are explicitly multi-branch.
CREATE TABLE IF NOT EXISTS teacher_branch_assignments (
  id TEXT PRIMARY KEY,
  teacher_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  assigned_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  assigned_at TEXT NOT NULL,
  UNIQUE (teacher_user_id, branch_id)
);
CREATE INDEX IF NOT EXISTS idx_teacher_branch_assignments_branch ON teacher_branch_assignments(branch_id);

-- =====================================================================
-- Academic dimension
-- =====================================================================

CREATE TABLE IF NOT EXISTS academic_years (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL UNIQUE,
  start_date TEXT,
  end_date TEXT,
  is_current BOOLEAN NOT NULL DEFAULT false,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS terms (
  id TEXT PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_fr TEXT NOT NULL DEFAULT '',
  "order" INTEGER NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT true
);

-- Classes are academic-year instances: Branch A / 3A / 2026–2027 differs
-- from Branch A / 3A / 2027–2028. Branch is carried on the class itself.
CREATE TABLE IF NOT EXISTS classes (
  id TEXT PRIMARY KEY,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  academic_year_id TEXT NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE,
  name_ar TEXT NOT NULL,
  name_fr TEXT NOT NULL DEFAULT '',
  level TEXT,
  section TEXT,
  capacity INTEGER,
  head_teacher_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TEXT NOT NULL,
  UNIQUE (branch_id, academic_year_id, name_ar)
);
CREATE INDEX IF NOT EXISTS idx_classes_branch ON classes(branch_id);
CREATE INDEX IF NOT EXISTS idx_classes_year ON classes(academic_year_id);

-- Global subject catalog.
CREATE TABLE IF NOT EXISTS subjects (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name_ar TEXT NOT NULL,
  name_fr TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TEXT NOT NULL
);

-- Branch/class-specific offering properties (coefficient, max score).
CREATE TABLE IF NOT EXISTS class_subjects (
  id TEXT PRIMARY KEY,
  class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  subject_id TEXT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  coefficient NUMERIC(6,2) NOT NULL DEFAULT 1,
  max_score NUMERIC(8,2) NOT NULL DEFAULT 20,
  active BOOLEAN NOT NULL DEFAULT true,
  UNIQUE (class_id, subject_id)
);
CREATE INDEX IF NOT EXISTS idx_class_subjects_subject ON class_subjects(subject_id);

-- Teacher → (class, subject) per academic year. Branch derived via class.
CREATE TABLE IF NOT EXISTS teaching_assignments (
  id TEXT PRIMARY KEY,
  teacher_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  subject_id TEXT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  academic_year_id TEXT NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE,
  assigned_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  assigned_at TEXT NOT NULL,
  UNIQUE (teacher_user_id, class_id, subject_id, academic_year_id)
);
CREATE INDEX IF NOT EXISTS idx_teaching_assignments_teacher ON teaching_assignments(teacher_user_id);
CREATE INDEX IF NOT EXISTS idx_teaching_assignments_class ON teaching_assignments(class_id);
CREATE INDEX IF NOT EXISTS idx_teaching_assignments_subject ON teaching_assignments(subject_id);

CREATE TABLE IF NOT EXISTS timetable_entries (
  id TEXT PRIMARY KEY,
  class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  day INTEGER NOT NULL,
  slot INTEGER NOT NULL,
  subject_id TEXT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  UNIQUE (class_id, day, slot)
);

CREATE TABLE IF NOT EXISTS exam_sessions (
  id TEXT PRIMARY KEY,
  term_id TEXT NOT NULL REFERENCES terms(id) ON DELETE CASCADE,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  date TEXT NOT NULL
);

-- Published bulletins (was the JSON publishedResults map).
CREATE TABLE IF NOT EXISTS published_results (
  class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  term_id TEXT NOT NULL REFERENCES terms(id) ON DELETE CASCADE,
  published BOOLEAN NOT NULL DEFAULT false,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (class_id, term_id)
);

-- =====================================================================
-- Students: current branch + movement history + class enrollments
-- =====================================================================

CREATE TABLE IF NOT EXISTS students (
  id TEXT PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_fr TEXT NOT NULL DEFAULT '',
  gender TEXT NOT NULL DEFAULT 'male',
  klass TEXT NOT NULL DEFAULT '',
  dob TEXT NOT NULL DEFAULT '',
  place_of_birth TEXT NOT NULL DEFAULT '',
  parent_ar TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  enrolled TEXT NOT NULL DEFAULT '',
  annual_fee NUMERIC(12,2) NOT NULL DEFAULT 0,
  photo TEXT,
  email TEXT NOT NULL DEFAULT '',
  branch_id TEXT NOT NULL REFERENCES branches(id),
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_students_branch ON students(branch_id);

CREATE TABLE IF NOT EXISTS student_branch_history (
  id TEXT PRIMARY KEY,
  student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  effective_date TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  is_current BOOLEAN NOT NULL DEFAULT false,
  moved_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_student_branch_history_student ON student_branch_history(student_id);

CREATE TABLE IF NOT EXISTS student_class_enrollments (
  id TEXT PRIMARY KEY,
  student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  academic_year_id TEXT NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'enrolled',
  enrolled_on TEXT NOT NULL DEFAULT '',
  left_on TEXT,
  note TEXT NOT NULL DEFAULT '',
  is_current BOOLEAN NOT NULL DEFAULT true,
  recorded_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE (student_id, class_id, academic_year_id),
  CHECK (status IN ('enrolled', 'promoted', 'transferred', 'left', 'graduated'))
);
CREATE INDEX IF NOT EXISTS idx_enrollments_class ON student_class_enrollments(class_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_student ON student_class_enrollments(student_id);

-- =====================================================================
-- Assessments & grades (multiple assessment types per subject/term)
-- =====================================================================

CREATE TABLE IF NOT EXISTS assessments (
  id TEXT PRIMARY KEY,
  class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  subject_id TEXT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  term_id TEXT NOT NULL REFERENCES terms(id) ON DELETE CASCADE,
  type_code TEXT NOT NULL REFERENCES assessment_types(code),
  title TEXT NOT NULL,
  date TEXT,
  max_score NUMERIC(8,2) NOT NULL DEFAULT 20,
  created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  UNIQUE (class_id, subject_id, term_id, type_code, title)
);
CREATE INDEX IF NOT EXISTS idx_assessments_class ON assessments(class_id);

CREATE TABLE IF NOT EXISTS grades (
  id TEXT PRIMARY KEY,
  student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  assessment_id TEXT NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,
  score NUMERIC(8,2) NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  recorded_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (student_id, assessment_id)
);
CREATE INDEX IF NOT EXISTS idx_grades_assessment ON grades(assessment_id);
CREATE INDEX IF NOT EXISTS idx_grades_student ON grades(student_id);

-- =====================================================================
-- Attendance & warnings
-- =====================================================================

CREATE TABLE IF NOT EXISTS attendance (
  id TEXT PRIMARY KEY,
  class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'present',
  marked_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  UNIQUE (class_id, student_id, date),
  CHECK (status IN ('present', 'absent', 'late'))
);
CREATE INDEX IF NOT EXISTS idx_attendance_class_date ON attendance(class_id, date);
CREATE INDEX IF NOT EXISTS idx_attendance_student ON attendance(student_id);

CREATE TABLE IF NOT EXISTS warnings (
  id TEXT PRIMARY KEY,
  student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  kind TEXT NOT NULL DEFAULT 'absence',
  date TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  CHECK (kind IN ('absence', 'behavior', 'academic'))
);
CREATE INDEX IF NOT EXISTS idx_warnings_student ON warnings(student_id);

-- =====================================================================
-- Finance
-- =====================================================================

CREATE TABLE IF NOT EXISTS fee_types (
  id TEXT PRIMARY KEY,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  name_ar TEXT NOT NULL,
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS idx_fee_types_branch ON fee_types(branch_id);

CREATE TABLE IF NOT EXISTS payments (
  id TEXT PRIMARY KEY,
  student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  date TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  recorded_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_payments_student ON payments(student_id);
CREATE INDEX IF NOT EXISTS idx_payments_branch ON payments(branch_id);

CREATE TABLE IF NOT EXISTS expenses (
  id TEXT PRIMARY KEY,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT '',
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  note TEXT NOT NULL DEFAULT '',
  vendor TEXT NOT NULL DEFAULT '',
  recorded_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_expenses_branch ON expenses(branch_id);

-- =====================================================================
-- Documents, notifications, audit (existing tables + branch targeting)
-- =====================================================================

CREATE TABLE IF NOT EXISTS documents (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  visibility TEXT NOT NULL,
  class_id TEXT,
  student_id TEXT,
  branch_id TEXT,
  filename TEXT NOT NULL,
  stored_name TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  mime TEXT NOT NULL,
  uploaded_by_user_id TEXT NOT NULL,
  uploaded_by_name TEXT NOT NULL DEFAULT '',
  archived BOOLEAN NOT NULL DEFAULT false,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_documents_created ON documents(created_at);
-- NOTE: idx_documents_branch lives in the bottom index block, AFTER the
-- backward-compat ALTERs (legacy documents rows have no branch_id column).

CREATE TABLE IF NOT EXISTS notifications (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL DEFAULT 'general',
  target TEXT NOT NULL,
  user_id TEXT,
  class_id TEXT,
  created_by_user_id TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS notification_branches (
  notification_id TEXT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
  branch_id TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  PRIMARY KEY (notification_id, branch_id)
);

CREATE TABLE IF NOT EXISTS notification_reads (
  notification_id TEXT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  read_at TEXT NOT NULL,
  PRIMARY KEY (notification_id, user_id)
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,
  action TEXT NOT NULL,
  actor_id TEXT,
  actor_name TEXT,
  target_id TEXT,
  target_name TEXT,
  branch_id TEXT,
  detail TEXT,
  entity_type TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);
-- NOTE: idx_audit_branch lives in the bottom index block, AFTER the
-- backward-compat ALTERs (legacy audit_logs rows have no branch_id column).

-- Site modules (unchanged).
CREATE TABLE IF NOT EXISTS contact_messages (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  read BOOLEAN NOT NULL DEFAULT false,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS site_news (
  id TEXT PRIMARY KEY,
  title_ar TEXT NOT NULL,
  title_fr TEXT NOT NULL DEFAULT '',
  title_en TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL,
  cover TEXT NOT NULL DEFAULT '',
  news_date TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT true,
  updated_by TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_news_date ON site_news(news_date);

CREATE TABLE IF NOT EXISTS site_settings (
  id TEXT PRIMARY KEY,
  settings TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Kept ONLY as a temporary backward-compat shim for the legacy frontend
-- document path (/api/school); not part of the Phase 2A data architecture.
CREATE TABLE IF NOT EXISTS school_documents (
  id TEXT PRIMARY KEY,
  schema_version INTEGER NOT NULL,
  document TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Backward-compat columns for databases created before these were
-- introduced (idempotent). MUST run BEFORE the index block below: on a legacy
-- database the tables already exist without these columns, and creating an
-- index on a missing column aborts the whole schema batch (production login
-- 500: column "branch_id" does not exist, from ComputeIndexAttrs).
ALTER TABLE users ADD COLUMN IF NOT EXISTS staff_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS student_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS duties TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS branch_id TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS branch_id TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_type TEXT NOT NULL DEFAULT '';

-- Legacy session index (kept for freshly created databases).
CREATE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications(created_at);

-- Branch indexes on legacy tables. These MUST stay after the ALTER block
-- above: databases created before branch_id existed would otherwise abort the
-- whole schema batch here (column "branch_id" does not exist).
CREATE INDEX IF NOT EXISTS idx_documents_branch ON documents(branch_id);
CREATE INDEX IF NOT EXISTS idx_audit_branch ON audit_logs(branch_id);
`;

/** Reference seed data for the lookup tables. */
export const SEED_LOOKUPS_SQL = `
INSERT INTO duties (code, label_ar, label_fr) VALUES
  ('registrar', 'أمين السجل (الطلاب)', 'Registraire'),
  ('academic', 'الشؤون الدراسية (الفصول والمواد)', 'Académique'),
  ('accountant', 'المحاسبة (الرسوم والدفعات)', 'Comptable'),
  ('supervisor', 'الإشراف (الحضور)', 'Surveillant')
ON CONFLICT (code) DO NOTHING;

INSERT INTO assessment_types (code, label_ar, label_fr, weight, sort_order) VALUES
  ('quiz', 'اختبار قصير', 'Quiz', 1, 1),
  ('assignment', 'واجب', 'Devoir', 2, 2),
  ('midterm', 'فروض منتصف الفصل', 'Composition', 3, 3),
  ('final', 'اختبار نهائي', 'Examen final', 4, 4),
  ('exam', 'امتحان', 'Examen', 4, 5),
  ('other', 'أخرى', 'Autre', 1, 6)
ON CONFLICT (code) DO NOTHING;
`;