/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as MarketingAdmissionsRouteImport } from './routes/_marketing/admissions'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingNewsRouteImport } from './routes/_marketing/news'
import { Route as MarketingProgramsRouteImport } from './routes/_marketing/programs'
import { Route as ApiAuditRouteImport } from './routes/api/audit'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiDocumentsRouteImport } from './routes/api/documents'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiSchoolRouteImport } from './routes/api/school'
import { Route as ApiSiteSettingsRouteImport } from './routes/api/site-settings'
import { Route as ApiStudentRouteImport } from './routes/api/student'
import { Route as ApiTeacherRouteImport } from './routes/api/teacher'
import { Route as ApiTeachersRouteImport } from './routes/api/teachers'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as AppAcademicRouteImport } from './routes/app/academic'
import { Route as AppAccountantRouteImport } from './routes/app/accountant'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppRegistrarRouteImport } from './routes/app/registrar'
import { Route as AppStaffRouteImport } from './routes/app/staff'
import { Route as AppStudentRouteImport } from './routes/app/student'
import { Route as AppSupervisorRouteImport } from './routes/app/supervisor'
import { Route as AppTeacherRouteImport } from './routes/app/teacher'
import { Route as MediaFileRouteImport } from './routes/media/$file'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiMediaCoverRouteImport } from './routes/api/media/cover'
import { Route as ApiNewsIdRouteImport } from './routes/api/news/$id'
import { Route as ApiNewsManageRouteImport } from './routes/api/news/manage'
import { Route as ApiNotificationsReadRouteImport } from './routes/api/notifications/read'
import { Route as ApiNotificationsSentRouteImport } from './routes/api/notifications/sent'
import { Route as ApiUsersIdRouteImport } from './routes/api/users/$id'
import { Route as ApiUsersMigrateRouteImport } from './routes/api/users/migrate'
import { Route as ApiDocumentsIdArchiveRouteImport } from './routes/api/documents/$id/archive'
import { Route as ApiDocumentsIdDownloadRouteImport } from './routes/api/documents/$id/download'
import { Route as ApiUsersIdResetPasswordRouteImport } from './routes/api/users/$id/reset-password'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAdmissionsRoute = MarketingAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingNewsRoute = MarketingNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingProgramsRoute = MarketingProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => MarketingRoute,
} as any)
const ApiAuditRoute = ApiAuditRouteImport.update({
  id: '/api/audit',
  path: '/api/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchoolRoute = ApiSchoolRouteImport.update({
  id: '/api/school',
  path: '/api/school',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteSettingsRoute = ApiSiteSettingsRouteImport.update({
  id: '/api/site-settings',
  path: '/api/site-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentRoute = ApiStudentRouteImport.update({
  id: '/api/student',
  path: '/api/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeacherRoute = ApiTeacherRouteImport.update({
  id: '/api/teacher',
  path: '/api/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeachersRoute = ApiTeachersRouteImport.update({
  id: '/api/teachers',
  path: '/api/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAcademicRoute = AppAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountantRoute = AppAccountantRouteImport.update({
  id: '/accountant',
  path: '/accountant',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistrarRoute = AppRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentRoute = AppStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisorRoute = AppSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherRoute = AppTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AppRoute,
} as any)
const MediaFileRoute = MediaFileRouteImport.update({
  id: '/media/$file',
  path: '/media/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaCoverRoute = ApiMediaCoverRouteImport.update({
  id: '/api/media/cover',
  path: '/api/media/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsIdRoute = ApiNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNewsRoute,
} as any)
const ApiNewsManageRoute = ApiNewsManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => ApiNewsRoute,
} as any)
const ApiNotificationsReadRoute = ApiNotificationsReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => ApiNotificationsRoute,
} as any)
const ApiNotificationsSentRoute = ApiNotificationsSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => ApiNotificationsRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiUsersMigrateRoute = ApiUsersMigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiDocumentsIdArchiveRoute = ApiDocumentsIdArchiveRouteImport.update({
  id: '/$id/archive',
  path: '/$id/archive',
  getParentRoute: () => ApiDocumentsRoute,
} as any)
const ApiDocumentsIdDownloadRoute = ApiDocumentsIdDownloadRouteImport.update({
  id: '/$id/download',
  path: '/$id/download',
  getParentRoute: () => ApiDocumentsRoute,
} as any)
const ApiUsersIdResetPasswordRoute = ApiUsersIdResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => ApiUsersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/about': typeof MarketingAboutRoute
  '/admissions': typeof MarketingAdmissionsRoute
  '/contact': typeof MarketingContactRoute
  '/news': typeof MarketingNewsRoute
  '/programs': typeof MarketingProgramsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/contact': typeof ApiContactRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/school': typeof ApiSchoolRoute
  '/api/site-settings': typeof ApiSiteSettingsRoute
  '/api/student': typeof ApiStudentRoute
  '/api/teacher': typeof ApiTeacherRoute
  '/api/teachers': typeof ApiTeachersRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app/academic': typeof AppAcademicRoute
  '/app/accountant': typeof AppAccountantRoute
  '/app/admin': typeof AppAdminRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/app/staff': typeof AppStaffRoute
  '/app/student': typeof AppStudentRoute
  '/app/supervisor': typeof AppSupervisorRoute
  '/app/teacher': typeof AppTeacherRoute
  '/media/$file': typeof MediaFileRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/media/cover': typeof ApiMediaCoverRoute
  '/api/news/$id': typeof ApiNewsIdRoute
  '/api/news/manage': typeof ApiNewsManageRoute
  '/api/notifications/read': typeof ApiNotificationsReadRoute
  '/api/notifications/sent': typeof ApiNotificationsSentRoute
  '/api/users/$id': typeof ApiUsersIdRouteWithChildren
  '/api/users/migrate': typeof ApiUsersMigrateRoute
  '/api/documents/$id/archive': typeof ApiDocumentsIdArchiveRoute
  '/api/documents/$id/download': typeof ApiDocumentsIdDownloadRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/about': typeof MarketingAboutRoute
  '/admissions': typeof MarketingAdmissionsRoute
  '/contact': typeof MarketingContactRoute
  '/news': typeof MarketingNewsRoute
  '/programs': typeof MarketingProgramsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/contact': typeof ApiContactRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/school': typeof ApiSchoolRoute
  '/api/site-settings': typeof ApiSiteSettingsRoute
  '/api/student': typeof ApiStudentRoute
  '/api/teacher': typeof ApiTeacherRoute
  '/api/teachers': typeof ApiTeachersRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app/academic': typeof AppAcademicRoute
  '/app/accountant': typeof AppAccountantRoute
  '/app/admin': typeof AppAdminRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/app/staff': typeof AppStaffRoute
  '/app/student': typeof AppStudentRoute
  '/app/supervisor': typeof AppSupervisorRoute
  '/app/teacher': typeof AppTeacherRoute
  '/media/$file': typeof MediaFileRoute
  '/': typeof MarketingIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/media/cover': typeof ApiMediaCoverRoute
  '/api/news/$id': typeof ApiNewsIdRoute
  '/api/news/manage': typeof ApiNewsManageRoute
  '/api/notifications/read': typeof ApiNotificationsReadRoute
  '/api/notifications/sent': typeof ApiNotificationsSentRoute
  '/api/users/$id': typeof ApiUsersIdRouteWithChildren
  '/api/users/migrate': typeof ApiUsersMigrateRoute
  '/api/documents/$id/archive': typeof ApiDocumentsIdArchiveRoute
  '/api/documents/$id/download': typeof ApiDocumentsIdDownloadRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/admissions': typeof MarketingAdmissionsRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/news': typeof MarketingNewsRoute
  '/_marketing/programs': typeof MarketingProgramsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/contact': typeof ApiContactRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/school': typeof ApiSchoolRoute
  '/api/site-settings': typeof ApiSiteSettingsRoute
  '/api/student': typeof ApiStudentRoute
  '/api/teacher': typeof ApiTeacherRoute
  '/api/teachers': typeof ApiTeachersRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app/academic': typeof AppAcademicRoute
  '/app/accountant': typeof AppAccountantRoute
  '/app/admin': typeof AppAdminRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/app/staff': typeof AppStaffRoute
  '/app/student': typeof AppStudentRoute
  '/app/supervisor': typeof AppSupervisorRoute
  '/app/teacher': typeof AppTeacherRoute
  '/media/$file': typeof MediaFileRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/media/cover': typeof ApiMediaCoverRoute
  '/api/news/$id': typeof ApiNewsIdRoute
  '/api/news/manage': typeof ApiNewsManageRoute
  '/api/notifications/read': typeof ApiNotificationsReadRoute
  '/api/notifications/sent': typeof ApiNotificationsSentRoute
  '/api/users/$id': typeof ApiUsersIdRouteWithChildren
  '/api/users/migrate': typeof ApiUsersMigrateRoute
  '/api/documents/$id/archive': typeof ApiDocumentsIdArchiveRoute
  '/api/documents/$id/download': typeof ApiDocumentsIdDownloadRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/welcome'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/news'
    | '/programs'
    | '/api/audit'
    | '/api/contact'
    | '/api/documents'
    | '/api/news'
    | '/api/notifications'
    | '/api/school'
    | '/api/site-settings'
    | '/api/student'
    | '/api/teacher'
    | '/api/teachers'
    | '/api/users'
    | '/app/academic'
    | '/app/accountant'
    | '/app/admin'
    | '/app/registrar'
    | '/app/staff'
    | '/app/student'
    | '/app/supervisor'
    | '/app/teacher'
    | '/media/$file'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/media/cover'
    | '/api/news/$id'
    | '/api/news/manage'
    | '/api/notifications/read'
    | '/api/notifications/sent'
    | '/api/users/$id'
    | '/api/users/migrate'
    | '/api/documents/$id/archive'
    | '/api/documents/$id/download'
    | '/api/users/$id/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/login'
    | '/welcome'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/news'
    | '/programs'
    | '/api/audit'
    | '/api/contact'
    | '/api/documents'
    | '/api/news'
    | '/api/notifications'
    | '/api/school'
    | '/api/site-settings'
    | '/api/student'
    | '/api/teacher'
    | '/api/teachers'
    | '/api/users'
    | '/app/academic'
    | '/app/accountant'
    | '/app/admin'
    | '/app/registrar'
    | '/app/staff'
    | '/app/student'
    | '/app/supervisor'
    | '/app/teacher'
    | '/media/$file'
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/media/cover'
    | '/api/news/$id'
    | '/api/news/manage'
    | '/api/notifications/read'
    | '/api/notifications/sent'
    | '/api/users/$id'
    | '/api/users/migrate'
    | '/api/documents/$id/archive'
    | '/api/documents/$id/download'
    | '/api/users/$id/reset-password'
  id:
    | '__root__'
    | '/_marketing'
    | '/app'
    | '/login'
    | '/welcome'
    | '/_marketing/about'
    | '/_marketing/admissions'
    | '/_marketing/contact'
    | '/_marketing/news'
    | '/_marketing/programs'
    | '/api/audit'
    | '/api/contact'
    | '/api/documents'
    | '/api/news'
    | '/api/notifications'
    | '/api/school'
    | '/api/site-settings'
    | '/api/student'
    | '/api/teacher'
    | '/api/teachers'
    | '/api/users'
    | '/app/academic'
    | '/app/accountant'
    | '/app/admin'
    | '/app/registrar'
    | '/app/staff'
    | '/app/student'
    | '/app/supervisor'
    | '/app/teacher'
    | '/media/$file'
    | '/_marketing/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/media/cover'
    | '/api/news/$id'
    | '/api/news/manage'
    | '/api/notifications/read'
    | '/api/notifications/sent'
    | '/api/users/$id'
    | '/api/users/migrate'
    | '/api/documents/$id/archive'
    | '/api/documents/$id/download'
    | '/api/users/$id/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiAuditRoute: typeof ApiAuditRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiDocumentsRoute: typeof ApiDocumentsRouteWithChildren
  ApiNewsRoute: typeof ApiNewsRouteWithChildren
  ApiNotificationsRoute: typeof ApiNotificationsRouteWithChildren
  ApiSchoolRoute: typeof ApiSchoolRoute
  ApiSiteSettingsRoute: typeof ApiSiteSettingsRoute
  ApiStudentRoute: typeof ApiStudentRoute
  ApiTeacherRoute: typeof ApiTeacherRoute
  ApiTeachersRoute: typeof ApiTeachersRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  MediaFileRoute: typeof MediaFileRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiMediaCoverRoute: typeof ApiMediaCoverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/admissions': {
      id: '/_marketing/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof MarketingAdmissionsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/news': {
      id: '/_marketing/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof MarketingNewsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/programs': {
      id: '/_marketing/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof MarketingProgramsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/audit': {
      id: '/api/audit'
      path: '/api/audit'
      fullPath: '/api/audit'
      preLoaderRoute: typeof ApiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/school': {
      id: '/api/school'
      path: '/api/school'
      fullPath: '/api/school'
      preLoaderRoute: typeof ApiSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-settings': {
      id: '/api/site-settings'
      path: '/api/site-settings'
      fullPath: '/api/site-settings'
      preLoaderRoute: typeof ApiSiteSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/student': {
      id: '/api/student'
      path: '/api/student'
      fullPath: '/api/student'
      preLoaderRoute: typeof ApiStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teacher': {
      id: '/api/teacher'
      path: '/api/teacher'
      fullPath: '/api/teacher'
      preLoaderRoute: typeof ApiTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teachers': {
      id: '/api/teachers'
      path: '/api/teachers'
      fullPath: '/api/teachers'
      preLoaderRoute: typeof ApiTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/academic': {
      id: '/app/academic'
      path: '/academic'
      fullPath: '/app/academic'
      preLoaderRoute: typeof AppAcademicRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accountant': {
      id: '/app/accountant'
      path: '/accountant'
      fullPath: '/app/accountant'
      preLoaderRoute: typeof AppAccountantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registrar': {
      id: '/app/registrar'
      path: '/registrar'
      fullPath: '/app/registrar'
      preLoaderRoute: typeof AppRegistrarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student': {
      id: '/app/student'
      path: '/student'
      fullPath: '/app/student'
      preLoaderRoute: typeof AppStudentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/supervisor': {
      id: '/app/supervisor'
      path: '/supervisor'
      fullPath: '/app/supervisor'
      preLoaderRoute: typeof AppSupervisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher': {
      id: '/app/teacher'
      path: '/teacher'
      fullPath: '/app/teacher'
      preLoaderRoute: typeof AppTeacherRouteImport
      parentRoute: typeof AppRoute
    }
    '/media/$file': {
      id: '/media/$file'
      path: '/media/$file'
      fullPath: '/media/$file'
      preLoaderRoute: typeof MediaFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/cover': {
      id: '/api/media/cover'
      path: '/api/media/cover'
      fullPath: '/api/media/cover'
      preLoaderRoute: typeof ApiMediaCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/$id': {
      id: '/api/news/$id'
      path: '/$id'
      fullPath: '/api/news/$id'
      preLoaderRoute: typeof ApiNewsIdRouteImport
      parentRoute: typeof ApiNewsRoute
    }
    '/api/news/manage': {
      id: '/api/news/manage'
      path: '/manage'
      fullPath: '/api/news/manage'
      preLoaderRoute: typeof ApiNewsManageRouteImport
      parentRoute: typeof ApiNewsRoute
    }
    '/api/notifications/read': {
      id: '/api/notifications/read'
      path: '/read'
      fullPath: '/api/notifications/read'
      preLoaderRoute: typeof ApiNotificationsReadRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/notifications/sent': {
      id: '/api/notifications/sent'
      path: '/sent'
      fullPath: '/api/notifications/sent'
      preLoaderRoute: typeof ApiNotificationsSentRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/users/migrate': {
      id: '/api/users/migrate'
      path: '/migrate'
      fullPath: '/api/users/migrate'
      preLoaderRoute: typeof ApiUsersMigrateRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/documents/$id/archive': {
      id: '/api/documents/$id/archive'
      path: '/$id/archive'
      fullPath: '/api/documents/$id/archive'
      preLoaderRoute: typeof ApiDocumentsIdArchiveRouteImport
      parentRoute: typeof ApiDocumentsRoute
    }
    '/api/documents/$id/download': {
      id: '/api/documents/$id/download'
      path: '/$id/download'
      fullPath: '/api/documents/$id/download'
      preLoaderRoute: typeof ApiDocumentsIdDownloadRouteImport
      parentRoute: typeof ApiDocumentsRoute
    }
    '/api/users/$id/reset-password': {
      id: '/api/users/$id/reset-password'
      path: '/reset-password'
      fullPath: '/api/users/$id/reset-password'
      preLoaderRoute: typeof ApiUsersIdResetPasswordRouteImport
      parentRoute: typeof ApiUsersIdRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingAdmissionsRoute: typeof MarketingAdmissionsRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingNewsRoute: typeof MarketingNewsRoute
  MarketingProgramsRoute: typeof MarketingProgramsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingAdmissionsRoute: MarketingAdmissionsRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingNewsRoute: MarketingNewsRoute,
  MarketingProgramsRoute: MarketingProgramsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AppRouteChildren {
  AppAcademicRoute: typeof AppAcademicRoute
  AppAccountantRoute: typeof AppAccountantRoute
  AppAdminRoute: typeof AppAdminRoute
  AppRegistrarRoute: typeof AppRegistrarRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStudentRoute: typeof AppStudentRoute
  AppSupervisorRoute: typeof AppSupervisorRoute
  AppTeacherRoute: typeof AppTeacherRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicRoute: AppAcademicRoute,
  AppAccountantRoute: AppAccountantRoute,
  AppAdminRoute: AppAdminRoute,
  AppRegistrarRoute: AppRegistrarRoute,
  AppStaffRoute: AppStaffRoute,
  AppStudentRoute: AppStudentRoute,
  AppSupervisorRoute: AppSupervisorRoute,
  AppTeacherRoute: AppTeacherRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiDocumentsRouteChildren {
  ApiDocumentsIdArchiveRoute: typeof ApiDocumentsIdArchiveRoute
  ApiDocumentsIdDownloadRoute: typeof ApiDocumentsIdDownloadRoute
}

const ApiDocumentsRouteChildren: ApiDocumentsRouteChildren = {
  ApiDocumentsIdArchiveRoute: ApiDocumentsIdArchiveRoute,
  ApiDocumentsIdDownloadRoute: ApiDocumentsIdDownloadRoute,
}

const ApiDocumentsRouteWithChildren = ApiDocumentsRoute._addFileChildren(
  ApiDocumentsRouteChildren,
)

interface ApiNewsRouteChildren {
  ApiNewsIdRoute: typeof ApiNewsIdRoute
  ApiNewsManageRoute: typeof ApiNewsManageRoute
}

const ApiNewsRouteChildren: ApiNewsRouteChildren = {
  ApiNewsIdRoute: ApiNewsIdRoute,
  ApiNewsManageRoute: ApiNewsManageRoute,
}

const ApiNewsRouteWithChildren =
  ApiNewsRoute._addFileChildren(ApiNewsRouteChildren)

interface ApiNotificationsRouteChildren {
  ApiNotificationsReadRoute: typeof ApiNotificationsReadRoute
  ApiNotificationsSentRoute: typeof ApiNotificationsSentRoute
}

const ApiNotificationsRouteChildren: ApiNotificationsRouteChildren = {
  ApiNotificationsReadRoute: ApiNotificationsReadRoute,
  ApiNotificationsSentRoute: ApiNotificationsSentRoute,
}

const ApiNotificationsRouteWithChildren =
  ApiNotificationsRoute._addFileChildren(ApiNotificationsRouteChildren)

interface ApiUsersIdRouteChildren {
  ApiUsersIdResetPasswordRoute: typeof ApiUsersIdResetPasswordRoute
}

const ApiUsersIdRouteChildren: ApiUsersIdRouteChildren = {
  ApiUsersIdResetPasswordRoute: ApiUsersIdResetPasswordRoute,
}

const ApiUsersIdRouteWithChildren = ApiUsersIdRoute._addFileChildren(
  ApiUsersIdRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRouteWithChildren
  ApiUsersMigrateRoute: typeof ApiUsersMigrateRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRouteWithChildren,
  ApiUsersMigrateRoute: ApiUsersMigrateRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
  ApiAuditRoute: ApiAuditRoute,
  ApiContactRoute: ApiContactRoute,
  ApiDocumentsRoute: ApiDocumentsRouteWithChildren,
  ApiNewsRoute: ApiNewsRouteWithChildren,
  ApiNotificationsRoute: ApiNotificationsRouteWithChildren,
  ApiSchoolRoute: ApiSchoolRoute,
  ApiSiteSettingsRoute: ApiSiteSettingsRoute,
  ApiStudentRoute: ApiStudentRoute,
  ApiTeacherRoute: ApiTeacherRoute,
  ApiTeachersRoute: ApiTeachersRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  MediaFileRoute: MediaFileRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiMediaCoverRoute: ApiMediaCoverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
