/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as MarketingAdmissionsRouteImport } from './routes/_marketing/admissions'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingNewsRouteImport } from './routes/_marketing/news'
import { Route as MarketingProgramsRouteImport } from './routes/_marketing/programs'
import { Route as ApiAuditRouteImport } from './routes/api/audit'
import { Route as ApiBranchesRouteImport } from './routes/api/branches'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiDocumentsRouteImport } from './routes/api/documents'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiSchoolRouteImport } from './routes/api/school'
import { Route as ApiSiteSettingsRouteImport } from './routes/api/site-settings'
import { Route as ApiStudentRouteImport } from './routes/api/student'
import { Route as ApiStudentsRouteImport } from './routes/api/students'
import { Route as ApiTeacherRouteImport } from './routes/api/teacher'
import { Route as ApiTeachersRouteImport } from './routes/api/teachers'
import { Route as ApiTeachingAssignmentsRouteImport } from './routes/api/teaching-assignments'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as AppAcademicRouteImport } from './routes/app/academic'
import { Route as AppAccountantRouteImport } from './routes/app/accountant'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppRegistrarRouteImport } from './routes/app/registrar'
import { Route as AppStaffRouteImport } from './routes/app/staff'
import { Route as AppStudentRouteImport } from './routes/app/student'
import { Route as AppSupervisorRouteImport } from './routes/app/supervisor'
import { Route as AppTeacherRouteImport } from './routes/app/teacher'
import { Route as MediaFileRouteImport } from './routes/media/$file'
import { Route as ApiAcademicAssessmentTypesRouteImport } from './routes/api/academic/assessment-types'
import { Route as ApiAcademicAssessmentsRouteImport } from './routes/api/academic/assessments'
import { Route as ApiAcademicAttendanceRouteImport } from './routes/api/academic/attendance'
import { Route as ApiAcademicClassesRouteImport } from './routes/api/academic/classes'
import { Route as ApiAcademicExamSessionsRouteImport } from './routes/api/academic/exam-sessions'
import { Route as ApiAcademicGradesRouteImport } from './routes/api/academic/grades'
import { Route as ApiAcademicSubjectsRouteImport } from './routes/api/academic/subjects'
import { Route as ApiAcademicTermsRouteImport } from './routes/api/academic/terms'
import { Route as ApiAcademicWarningsRouteImport } from './routes/api/academic/warnings'
import { Route as ApiAcademicYearsRouteImport } from './routes/api/academic/years'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiBranchesIdRouteImport } from './routes/api/branches/$id'
import { Route as ApiFinanceExpensesRouteImport } from './routes/api/finance/expenses'
import { Route as ApiFinanceFeeTypesRouteImport } from './routes/api/finance/fee-types'
import { Route as ApiFinancePaymentsRouteImport } from './routes/api/finance/payments'
import { Route as ApiMediaCoverRouteImport } from './routes/api/media/cover'
import { Route as ApiNewsIdRouteImport } from './routes/api/news/$id'
import { Route as ApiNewsManageRouteImport } from './routes/api/news/manage'
import { Route as ApiNotificationsReadRouteImport } from './routes/api/notifications/read'
import { Route as ApiNotificationsSentRouteImport } from './routes/api/notifications/sent'
import { Route as ApiStudentsIdRouteImport } from './routes/api/students/$id'
import { Route as ApiStudentsMeRouteImport } from './routes/api/students/me'
import { Route as ApiTeachersIdRouteImport } from './routes/api/teachers/$id'
import { Route as ApiTeachingAssignmentsIdRouteImport } from './routes/api/teaching-assignments/$id'
import { Route as ApiUsersIdRouteImport } from './routes/api/users/$id'
import { Route as ApiUsersMigrateRouteImport } from './routes/api/users/migrate'
import { Route as ApiAcademicAssessmentsIdRouteImport } from './routes/api/academic/assessments/$id'
import { Route as ApiAcademicAttendanceIdRouteImport } from './routes/api/academic/attendance/$id'
import { Route as ApiAcademicClassesIdRouteImport } from './routes/api/academic/classes/$id'
import { Route as ApiAcademicExamSessionsIdRouteImport } from './routes/api/academic/exam-sessions/$id'
import { Route as ApiAcademicGradesIdRouteImport } from './routes/api/academic/grades/$id'
import { Route as ApiAcademicSubjectsIdRouteImport } from './routes/api/academic/subjects/$id'
import { Route as ApiAcademicTermsIdRouteImport } from './routes/api/academic/terms/$id'
import { Route as ApiAcademicWarningsIdRouteImport } from './routes/api/academic/warnings/$id'
import { Route as ApiAcademicYearsIdRouteImport } from './routes/api/academic/years/$id'
import { Route as ApiBranchesIdBranchHeadRouteImport } from './routes/api/branches/$id/branch-head'
import { Route as ApiBranchesIdDutiesRouteImport } from './routes/api/branches/$id/duties'
import { Route as ApiBranchesIdFinancialOfficerRouteImport } from './routes/api/branches/$id/financial-officer'
import { Route as ApiBranchesIdMembersRouteImport } from './routes/api/branches/$id/members'
import { Route as ApiBranchesIdTeachersRouteImport } from './routes/api/branches/$id/teachers'
import { Route as ApiDocumentsIdArchiveRouteImport } from './routes/api/documents/$id/archive'
import { Route as ApiDocumentsIdDownloadRouteImport } from './routes/api/documents/$id/download'
import { Route as ApiFinanceExpensesIdRouteImport } from './routes/api/finance/expenses/$id'
import { Route as ApiFinanceFeeTypesIdRouteImport } from './routes/api/finance/fee-types/$id'
import { Route as ApiFinancePaymentsIdRouteImport } from './routes/api/finance/payments/$id'
import { Route as ApiStudentsIdPromoteRouteImport } from './routes/api/students/$id/promote'
import { Route as ApiStudentsIdTransferRouteImport } from './routes/api/students/$id/transfer'
import { Route as ApiUsersIdResetPasswordRouteImport } from './routes/api/users/$id/reset-password'
import { Route as ApiAcademicClassesIdClassSubjectsRouteImport } from './routes/api/academic/classes/$id/class-subjects'
import { Route as ApiAcademicClassesIdResultsRouteImport } from './routes/api/academic/classes/$id/results'
import { Route as ApiAcademicClassesIdTimetableRouteImport } from './routes/api/academic/classes/$id/timetable'
import { Route as ApiAcademicClassesIdTransferRouteImport } from './routes/api/academic/classes/$id/transfer'
import { Route as ApiBranchesIdDutiesResponsibilityIdRouteImport } from './routes/api/branches/$id/duties/$responsibilityId'
import { Route as ApiAcademicClassesIdClassSubjectsSubjectIdRouteImport } from './routes/api/academic/classes/$id/class-subjects/$subjectId'
import { Route as ApiAcademicClassesIdTimetableEntryIdRouteImport } from './routes/api/academic/classes/$id/timetable/$entryId'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAdmissionsRoute = MarketingAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingNewsRoute = MarketingNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingProgramsRoute = MarketingProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => MarketingRoute,
} as any)
const ApiAuditRoute = ApiAuditRouteImport.update({
  id: '/api/audit',
  path: '/api/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBranchesRoute = ApiBranchesRouteImport.update({
  id: '/api/branches',
  path: '/api/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchoolRoute = ApiSchoolRouteImport.update({
  id: '/api/school',
  path: '/api/school',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteSettingsRoute = ApiSiteSettingsRouteImport.update({
  id: '/api/site-settings',
  path: '/api/site-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentRoute = ApiStudentRouteImport.update({
  id: '/api/student',
  path: '/api/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsRoute = ApiStudentsRouteImport.update({
  id: '/api/students',
  path: '/api/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeacherRoute = ApiTeacherRouteImport.update({
  id: '/api/teacher',
  path: '/api/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeachersRoute = ApiTeachersRouteImport.update({
  id: '/api/teachers',
  path: '/api/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeachingAssignmentsRoute = ApiTeachingAssignmentsRouteImport.update({
  id: '/api/teaching-assignments',
  path: '/api/teaching-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAcademicRoute = AppAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountantRoute = AppAccountantRouteImport.update({
  id: '/accountant',
  path: '/accountant',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistrarRoute = AppRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentRoute = AppStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisorRoute = AppSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherRoute = AppTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AppRoute,
} as any)
const MediaFileRoute = MediaFileRouteImport.update({
  id: '/media/$file',
  path: '/media/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademicAssessmentTypesRoute =
  ApiAcademicAssessmentTypesRouteImport.update({
    id: '/api/academic/assessment-types',
    path: '/api/academic/assessment-types',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAcademicAssessmentsRoute = ApiAcademicAssessmentsRouteImport.update({
  id: '/api/academic/assessments',
  path: '/api/academic/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademicAttendanceRoute = ApiAcademicAttendanceRouteImport.update({
  id: '/api/academic/attendance',
  path: '/api/academic/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademicClassesRoute = ApiAcademicClassesRouteImport.update({
  id: '/api/academic/classes',
  path: '/api/academic/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademicExamSessionsRoute = ApiAcademicExamSessionsRouteImport.update({
  id: '/api/academic/exam-sessions',
  path: '/api/academic/exam-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademicGradesRoute = ApiAcademicGradesRouteImport.update({
  id: '/api/academic/grades',
  path: '/api/academic/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademicSubjectsRoute = ApiAcademicSubjectsRouteImport.update({
  id: '/api/academic/subjects',
  path: '/api/academic/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademicTermsRoute = ApiAcademicTermsRouteImport.update({
  id: '/api/academic/terms',
  path: '/api/academic/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademicWarningsRoute = ApiAcademicWarningsRouteImport.update({
  id: '/api/academic/warnings',
  path: '/api/academic/warnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcademicYearsRoute = ApiAcademicYearsRouteImport.update({
  id: '/api/academic/years',
  path: '/api/academic/years',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBranchesIdRoute = ApiBranchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiBranchesRoute,
} as any)
const ApiFinanceExpensesRoute = ApiFinanceExpensesRouteImport.update({
  id: '/api/finance/expenses',
  path: '/api/finance/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceFeeTypesRoute = ApiFinanceFeeTypesRouteImport.update({
  id: '/api/finance/fee-types',
  path: '/api/finance/fee-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinancePaymentsRoute = ApiFinancePaymentsRouteImport.update({
  id: '/api/finance/payments',
  path: '/api/finance/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaCoverRoute = ApiMediaCoverRouteImport.update({
  id: '/api/media/cover',
  path: '/api/media/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsIdRoute = ApiNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNewsRoute,
} as any)
const ApiNewsManageRoute = ApiNewsManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => ApiNewsRoute,
} as any)
const ApiNotificationsReadRoute = ApiNotificationsReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => ApiNotificationsRoute,
} as any)
const ApiNotificationsSentRoute = ApiNotificationsSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => ApiNotificationsRoute,
} as any)
const ApiStudentsIdRoute = ApiStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStudentsRoute,
} as any)
const ApiStudentsMeRoute = ApiStudentsMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ApiStudentsRoute,
} as any)
const ApiTeachersIdRoute = ApiTeachersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTeachersRoute,
} as any)
const ApiTeachingAssignmentsIdRoute =
  ApiTeachingAssignmentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiTeachingAssignmentsRoute,
  } as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiUsersMigrateRoute = ApiUsersMigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAcademicAssessmentsIdRoute =
  ApiAcademicAssessmentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiAcademicAssessmentsRoute,
  } as any)
const ApiAcademicAttendanceIdRoute = ApiAcademicAttendanceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAcademicAttendanceRoute,
} as any)
const ApiAcademicClassesIdRoute = ApiAcademicClassesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAcademicClassesRoute,
} as any)
const ApiAcademicExamSessionsIdRoute =
  ApiAcademicExamSessionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiAcademicExamSessionsRoute,
  } as any)
const ApiAcademicGradesIdRoute = ApiAcademicGradesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAcademicGradesRoute,
} as any)
const ApiAcademicSubjectsIdRoute = ApiAcademicSubjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAcademicSubjectsRoute,
} as any)
const ApiAcademicTermsIdRoute = ApiAcademicTermsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAcademicTermsRoute,
} as any)
const ApiAcademicWarningsIdRoute = ApiAcademicWarningsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAcademicWarningsRoute,
} as any)
const ApiAcademicYearsIdRoute = ApiAcademicYearsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAcademicYearsRoute,
} as any)
const ApiBranchesIdBranchHeadRoute = ApiBranchesIdBranchHeadRouteImport.update({
  id: '/branch-head',
  path: '/branch-head',
  getParentRoute: () => ApiBranchesIdRoute,
} as any)
const ApiBranchesIdDutiesRoute = ApiBranchesIdDutiesRouteImport.update({
  id: '/duties',
  path: '/duties',
  getParentRoute: () => ApiBranchesIdRoute,
} as any)
const ApiBranchesIdFinancialOfficerRoute =
  ApiBranchesIdFinancialOfficerRouteImport.update({
    id: '/financial-officer',
    path: '/financial-officer',
    getParentRoute: () => ApiBranchesIdRoute,
  } as any)
const ApiBranchesIdMembersRoute = ApiBranchesIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiBranchesIdRoute,
} as any)
const ApiBranchesIdTeachersRoute = ApiBranchesIdTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => ApiBranchesIdRoute,
} as any)
const ApiDocumentsIdArchiveRoute = ApiDocumentsIdArchiveRouteImport.update({
  id: '/$id/archive',
  path: '/$id/archive',
  getParentRoute: () => ApiDocumentsRoute,
} as any)
const ApiDocumentsIdDownloadRoute = ApiDocumentsIdDownloadRouteImport.update({
  id: '/$id/download',
  path: '/$id/download',
  getParentRoute: () => ApiDocumentsRoute,
} as any)
const ApiFinanceExpensesIdRoute = ApiFinanceExpensesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFinanceExpensesRoute,
} as any)
const ApiFinanceFeeTypesIdRoute = ApiFinanceFeeTypesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFinanceFeeTypesRoute,
} as any)
const ApiFinancePaymentsIdRoute = ApiFinancePaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFinancePaymentsRoute,
} as any)
const ApiStudentsIdPromoteRoute = ApiStudentsIdPromoteRouteImport.update({
  id: '/promote',
  path: '/promote',
  getParentRoute: () => ApiStudentsIdRoute,
} as any)
const ApiStudentsIdTransferRoute = ApiStudentsIdTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => ApiStudentsIdRoute,
} as any)
const ApiUsersIdResetPasswordRoute = ApiUsersIdResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => ApiUsersIdRoute,
} as any)
const ApiAcademicClassesIdClassSubjectsRoute =
  ApiAcademicClassesIdClassSubjectsRouteImport.update({
    id: '/class-subjects',
    path: '/class-subjects',
    getParentRoute: () => ApiAcademicClassesIdRoute,
  } as any)
const ApiAcademicClassesIdResultsRoute =
  ApiAcademicClassesIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => ApiAcademicClassesIdRoute,
  } as any)
const ApiAcademicClassesIdTimetableRoute =
  ApiAcademicClassesIdTimetableRouteImport.update({
    id: '/timetable',
    path: '/timetable',
    getParentRoute: () => ApiAcademicClassesIdRoute,
  } as any)
const ApiAcademicClassesIdTransferRoute =
  ApiAcademicClassesIdTransferRouteImport.update({
    id: '/transfer',
    path: '/transfer',
    getParentRoute: () => ApiAcademicClassesIdRoute,
  } as any)
const ApiBranchesIdDutiesResponsibilityIdRoute =
  ApiBranchesIdDutiesResponsibilityIdRouteImport.update({
    id: '/$responsibilityId',
    path: '/$responsibilityId',
    getParentRoute: () => ApiBranchesIdDutiesRoute,
  } as any)
const ApiAcademicClassesIdClassSubjectsSubjectIdRoute =
  ApiAcademicClassesIdClassSubjectsSubjectIdRouteImport.update({
    id: '/$subjectId',
    path: '/$subjectId',
    getParentRoute: () => ApiAcademicClassesIdClassSubjectsRoute,
  } as any)
const ApiAcademicClassesIdTimetableEntryIdRoute =
  ApiAcademicClassesIdTimetableEntryIdRouteImport.update({
    id: '/$entryId',
    path: '/$entryId',
    getParentRoute: () => ApiAcademicClassesIdTimetableRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/about': typeof MarketingAboutRoute
  '/admissions': typeof MarketingAdmissionsRoute
  '/contact': typeof MarketingContactRoute
  '/news': typeof MarketingNewsRoute
  '/programs': typeof MarketingProgramsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/branches': typeof ApiBranchesRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/school': typeof ApiSchoolRoute
  '/api/site-settings': typeof ApiSiteSettingsRoute
  '/api/student': typeof ApiStudentRoute
  '/api/students': typeof ApiStudentsRouteWithChildren
  '/api/teacher': typeof ApiTeacherRoute
  '/api/teachers': typeof ApiTeachersRouteWithChildren
  '/api/teaching-assignments': typeof ApiTeachingAssignmentsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app/academic': typeof AppAcademicRoute
  '/app/accountant': typeof AppAccountantRoute
  '/app/admin': typeof AppAdminRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/app/staff': typeof AppStaffRoute
  '/app/student': typeof AppStudentRoute
  '/app/supervisor': typeof AppSupervisorRoute
  '/app/teacher': typeof AppTeacherRoute
  '/media/$file': typeof MediaFileRoute
  '/api/academic/assessment-types': typeof ApiAcademicAssessmentTypesRoute
  '/api/academic/assessments': typeof ApiAcademicAssessmentsRouteWithChildren
  '/api/academic/attendance': typeof ApiAcademicAttendanceRouteWithChildren
  '/api/academic/classes': typeof ApiAcademicClassesRouteWithChildren
  '/api/academic/exam-sessions': typeof ApiAcademicExamSessionsRouteWithChildren
  '/api/academic/grades': typeof ApiAcademicGradesRouteWithChildren
  '/api/academic/subjects': typeof ApiAcademicSubjectsRouteWithChildren
  '/api/academic/terms': typeof ApiAcademicTermsRouteWithChildren
  '/api/academic/warnings': typeof ApiAcademicWarningsRouteWithChildren
  '/api/academic/years': typeof ApiAcademicYearsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/branches/$id': typeof ApiBranchesIdRouteWithChildren
  '/api/finance/expenses': typeof ApiFinanceExpensesRouteWithChildren
  '/api/finance/fee-types': typeof ApiFinanceFeeTypesRouteWithChildren
  '/api/finance/payments': typeof ApiFinancePaymentsRouteWithChildren
  '/api/media/cover': typeof ApiMediaCoverRoute
  '/api/news/$id': typeof ApiNewsIdRoute
  '/api/news/manage': typeof ApiNewsManageRoute
  '/api/notifications/read': typeof ApiNotificationsReadRoute
  '/api/notifications/sent': typeof ApiNotificationsSentRoute
  '/api/students/$id': typeof ApiStudentsIdRouteWithChildren
  '/api/students/me': typeof ApiStudentsMeRoute
  '/api/teachers/$id': typeof ApiTeachersIdRoute
  '/api/teaching-assignments/$id': typeof ApiTeachingAssignmentsIdRoute
  '/api/users/$id': typeof ApiUsersIdRouteWithChildren
  '/api/users/migrate': typeof ApiUsersMigrateRoute
  '/api/academic/assessments/$id': typeof ApiAcademicAssessmentsIdRoute
  '/api/academic/attendance/$id': typeof ApiAcademicAttendanceIdRoute
  '/api/academic/classes/$id': typeof ApiAcademicClassesIdRouteWithChildren
  '/api/academic/exam-sessions/$id': typeof ApiAcademicExamSessionsIdRoute
  '/api/academic/grades/$id': typeof ApiAcademicGradesIdRoute
  '/api/academic/subjects/$id': typeof ApiAcademicSubjectsIdRoute
  '/api/academic/terms/$id': typeof ApiAcademicTermsIdRoute
  '/api/academic/warnings/$id': typeof ApiAcademicWarningsIdRoute
  '/api/academic/years/$id': typeof ApiAcademicYearsIdRoute
  '/api/branches/$id/branch-head': typeof ApiBranchesIdBranchHeadRoute
  '/api/branches/$id/duties': typeof ApiBranchesIdDutiesRouteWithChildren
  '/api/branches/$id/financial-officer': typeof ApiBranchesIdFinancialOfficerRoute
  '/api/branches/$id/members': typeof ApiBranchesIdMembersRoute
  '/api/branches/$id/teachers': typeof ApiBranchesIdTeachersRoute
  '/api/documents/$id/archive': typeof ApiDocumentsIdArchiveRoute
  '/api/documents/$id/download': typeof ApiDocumentsIdDownloadRoute
  '/api/finance/expenses/$id': typeof ApiFinanceExpensesIdRoute
  '/api/finance/fee-types/$id': typeof ApiFinanceFeeTypesIdRoute
  '/api/finance/payments/$id': typeof ApiFinancePaymentsIdRoute
  '/api/students/$id/promote': typeof ApiStudentsIdPromoteRoute
  '/api/students/$id/transfer': typeof ApiStudentsIdTransferRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
  '/api/academic/classes/$id/class-subjects': typeof ApiAcademicClassesIdClassSubjectsRouteWithChildren
  '/api/academic/classes/$id/results': typeof ApiAcademicClassesIdResultsRoute
  '/api/academic/classes/$id/timetable': typeof ApiAcademicClassesIdTimetableRouteWithChildren
  '/api/academic/classes/$id/transfer': typeof ApiAcademicClassesIdTransferRoute
  '/api/branches/$id/duties/$responsibilityId': typeof ApiBranchesIdDutiesResponsibilityIdRoute
  '/api/academic/classes/$id/class-subjects/$subjectId': typeof ApiAcademicClassesIdClassSubjectsSubjectIdRoute
  '/api/academic/classes/$id/timetable/$entryId': typeof ApiAcademicClassesIdTimetableEntryIdRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/about': typeof MarketingAboutRoute
  '/admissions': typeof MarketingAdmissionsRoute
  '/contact': typeof MarketingContactRoute
  '/news': typeof MarketingNewsRoute
  '/programs': typeof MarketingProgramsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/branches': typeof ApiBranchesRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/school': typeof ApiSchoolRoute
  '/api/site-settings': typeof ApiSiteSettingsRoute
  '/api/student': typeof ApiStudentRoute
  '/api/students': typeof ApiStudentsRouteWithChildren
  '/api/teacher': typeof ApiTeacherRoute
  '/api/teachers': typeof ApiTeachersRouteWithChildren
  '/api/teaching-assignments': typeof ApiTeachingAssignmentsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app/academic': typeof AppAcademicRoute
  '/app/accountant': typeof AppAccountantRoute
  '/app/admin': typeof AppAdminRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/app/staff': typeof AppStaffRoute
  '/app/student': typeof AppStudentRoute
  '/app/supervisor': typeof AppSupervisorRoute
  '/app/teacher': typeof AppTeacherRoute
  '/media/$file': typeof MediaFileRoute
  '/': typeof MarketingIndexRoute
  '/api/academic/assessment-types': typeof ApiAcademicAssessmentTypesRoute
  '/api/academic/assessments': typeof ApiAcademicAssessmentsRouteWithChildren
  '/api/academic/attendance': typeof ApiAcademicAttendanceRouteWithChildren
  '/api/academic/classes': typeof ApiAcademicClassesRouteWithChildren
  '/api/academic/exam-sessions': typeof ApiAcademicExamSessionsRouteWithChildren
  '/api/academic/grades': typeof ApiAcademicGradesRouteWithChildren
  '/api/academic/subjects': typeof ApiAcademicSubjectsRouteWithChildren
  '/api/academic/terms': typeof ApiAcademicTermsRouteWithChildren
  '/api/academic/warnings': typeof ApiAcademicWarningsRouteWithChildren
  '/api/academic/years': typeof ApiAcademicYearsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/branches/$id': typeof ApiBranchesIdRouteWithChildren
  '/api/finance/expenses': typeof ApiFinanceExpensesRouteWithChildren
  '/api/finance/fee-types': typeof ApiFinanceFeeTypesRouteWithChildren
  '/api/finance/payments': typeof ApiFinancePaymentsRouteWithChildren
  '/api/media/cover': typeof ApiMediaCoverRoute
  '/api/news/$id': typeof ApiNewsIdRoute
  '/api/news/manage': typeof ApiNewsManageRoute
  '/api/notifications/read': typeof ApiNotificationsReadRoute
  '/api/notifications/sent': typeof ApiNotificationsSentRoute
  '/api/students/$id': typeof ApiStudentsIdRouteWithChildren
  '/api/students/me': typeof ApiStudentsMeRoute
  '/api/teachers/$id': typeof ApiTeachersIdRoute
  '/api/teaching-assignments/$id': typeof ApiTeachingAssignmentsIdRoute
  '/api/users/$id': typeof ApiUsersIdRouteWithChildren
  '/api/users/migrate': typeof ApiUsersMigrateRoute
  '/api/academic/assessments/$id': typeof ApiAcademicAssessmentsIdRoute
  '/api/academic/attendance/$id': typeof ApiAcademicAttendanceIdRoute
  '/api/academic/classes/$id': typeof ApiAcademicClassesIdRouteWithChildren
  '/api/academic/exam-sessions/$id': typeof ApiAcademicExamSessionsIdRoute
  '/api/academic/grades/$id': typeof ApiAcademicGradesIdRoute
  '/api/academic/subjects/$id': typeof ApiAcademicSubjectsIdRoute
  '/api/academic/terms/$id': typeof ApiAcademicTermsIdRoute
  '/api/academic/warnings/$id': typeof ApiAcademicWarningsIdRoute
  '/api/academic/years/$id': typeof ApiAcademicYearsIdRoute
  '/api/branches/$id/branch-head': typeof ApiBranchesIdBranchHeadRoute
  '/api/branches/$id/duties': typeof ApiBranchesIdDutiesRouteWithChildren
  '/api/branches/$id/financial-officer': typeof ApiBranchesIdFinancialOfficerRoute
  '/api/branches/$id/members': typeof ApiBranchesIdMembersRoute
  '/api/branches/$id/teachers': typeof ApiBranchesIdTeachersRoute
  '/api/documents/$id/archive': typeof ApiDocumentsIdArchiveRoute
  '/api/documents/$id/download': typeof ApiDocumentsIdDownloadRoute
  '/api/finance/expenses/$id': typeof ApiFinanceExpensesIdRoute
  '/api/finance/fee-types/$id': typeof ApiFinanceFeeTypesIdRoute
  '/api/finance/payments/$id': typeof ApiFinancePaymentsIdRoute
  '/api/students/$id/promote': typeof ApiStudentsIdPromoteRoute
  '/api/students/$id/transfer': typeof ApiStudentsIdTransferRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
  '/api/academic/classes/$id/class-subjects': typeof ApiAcademicClassesIdClassSubjectsRouteWithChildren
  '/api/academic/classes/$id/results': typeof ApiAcademicClassesIdResultsRoute
  '/api/academic/classes/$id/timetable': typeof ApiAcademicClassesIdTimetableRouteWithChildren
  '/api/academic/classes/$id/transfer': typeof ApiAcademicClassesIdTransferRoute
  '/api/branches/$id/duties/$responsibilityId': typeof ApiBranchesIdDutiesResponsibilityIdRoute
  '/api/academic/classes/$id/class-subjects/$subjectId': typeof ApiAcademicClassesIdClassSubjectsSubjectIdRoute
  '/api/academic/classes/$id/timetable/$entryId': typeof ApiAcademicClassesIdTimetableEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/admissions': typeof MarketingAdmissionsRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/news': typeof MarketingNewsRoute
  '/_marketing/programs': typeof MarketingProgramsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/branches': typeof ApiBranchesRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/school': typeof ApiSchoolRoute
  '/api/site-settings': typeof ApiSiteSettingsRoute
  '/api/student': typeof ApiStudentRoute
  '/api/students': typeof ApiStudentsRouteWithChildren
  '/api/teacher': typeof ApiTeacherRoute
  '/api/teachers': typeof ApiTeachersRouteWithChildren
  '/api/teaching-assignments': typeof ApiTeachingAssignmentsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app/academic': typeof AppAcademicRoute
  '/app/accountant': typeof AppAccountantRoute
  '/app/admin': typeof AppAdminRoute
  '/app/registrar': typeof AppRegistrarRoute
  '/app/staff': typeof AppStaffRoute
  '/app/student': typeof AppStudentRoute
  '/app/supervisor': typeof AppSupervisorRoute
  '/app/teacher': typeof AppTeacherRoute
  '/media/$file': typeof MediaFileRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/api/academic/assessment-types': typeof ApiAcademicAssessmentTypesRoute
  '/api/academic/assessments': typeof ApiAcademicAssessmentsRouteWithChildren
  '/api/academic/attendance': typeof ApiAcademicAttendanceRouteWithChildren
  '/api/academic/classes': typeof ApiAcademicClassesRouteWithChildren
  '/api/academic/exam-sessions': typeof ApiAcademicExamSessionsRouteWithChildren
  '/api/academic/grades': typeof ApiAcademicGradesRouteWithChildren
  '/api/academic/subjects': typeof ApiAcademicSubjectsRouteWithChildren
  '/api/academic/terms': typeof ApiAcademicTermsRouteWithChildren
  '/api/academic/warnings': typeof ApiAcademicWarningsRouteWithChildren
  '/api/academic/years': typeof ApiAcademicYearsRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/branches/$id': typeof ApiBranchesIdRouteWithChildren
  '/api/finance/expenses': typeof ApiFinanceExpensesRouteWithChildren
  '/api/finance/fee-types': typeof ApiFinanceFeeTypesRouteWithChildren
  '/api/finance/payments': typeof ApiFinancePaymentsRouteWithChildren
  '/api/media/cover': typeof ApiMediaCoverRoute
  '/api/news/$id': typeof ApiNewsIdRoute
  '/api/news/manage': typeof ApiNewsManageRoute
  '/api/notifications/read': typeof ApiNotificationsReadRoute
  '/api/notifications/sent': typeof ApiNotificationsSentRoute
  '/api/students/$id': typeof ApiStudentsIdRouteWithChildren
  '/api/students/me': typeof ApiStudentsMeRoute
  '/api/teachers/$id': typeof ApiTeachersIdRoute
  '/api/teaching-assignments/$id': typeof ApiTeachingAssignmentsIdRoute
  '/api/users/$id': typeof ApiUsersIdRouteWithChildren
  '/api/users/migrate': typeof ApiUsersMigrateRoute
  '/api/academic/assessments/$id': typeof ApiAcademicAssessmentsIdRoute
  '/api/academic/attendance/$id': typeof ApiAcademicAttendanceIdRoute
  '/api/academic/classes/$id': typeof ApiAcademicClassesIdRouteWithChildren
  '/api/academic/exam-sessions/$id': typeof ApiAcademicExamSessionsIdRoute
  '/api/academic/grades/$id': typeof ApiAcademicGradesIdRoute
  '/api/academic/subjects/$id': typeof ApiAcademicSubjectsIdRoute
  '/api/academic/terms/$id': typeof ApiAcademicTermsIdRoute
  '/api/academic/warnings/$id': typeof ApiAcademicWarningsIdRoute
  '/api/academic/years/$id': typeof ApiAcademicYearsIdRoute
  '/api/branches/$id/branch-head': typeof ApiBranchesIdBranchHeadRoute
  '/api/branches/$id/duties': typeof ApiBranchesIdDutiesRouteWithChildren
  '/api/branches/$id/financial-officer': typeof ApiBranchesIdFinancialOfficerRoute
  '/api/branches/$id/members': typeof ApiBranchesIdMembersRoute
  '/api/branches/$id/teachers': typeof ApiBranchesIdTeachersRoute
  '/api/documents/$id/archive': typeof ApiDocumentsIdArchiveRoute
  '/api/documents/$id/download': typeof ApiDocumentsIdDownloadRoute
  '/api/finance/expenses/$id': typeof ApiFinanceExpensesIdRoute
  '/api/finance/fee-types/$id': typeof ApiFinanceFeeTypesIdRoute
  '/api/finance/payments/$id': typeof ApiFinancePaymentsIdRoute
  '/api/students/$id/promote': typeof ApiStudentsIdPromoteRoute
  '/api/students/$id/transfer': typeof ApiStudentsIdTransferRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
  '/api/academic/classes/$id/class-subjects': typeof ApiAcademicClassesIdClassSubjectsRouteWithChildren
  '/api/academic/classes/$id/results': typeof ApiAcademicClassesIdResultsRoute
  '/api/academic/classes/$id/timetable': typeof ApiAcademicClassesIdTimetableRouteWithChildren
  '/api/academic/classes/$id/transfer': typeof ApiAcademicClassesIdTransferRoute
  '/api/branches/$id/duties/$responsibilityId': typeof ApiBranchesIdDutiesResponsibilityIdRoute
  '/api/academic/classes/$id/class-subjects/$subjectId': typeof ApiAcademicClassesIdClassSubjectsSubjectIdRoute
  '/api/academic/classes/$id/timetable/$entryId': typeof ApiAcademicClassesIdTimetableEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/welcome'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/news'
    | '/programs'
    | '/api/audit'
    | '/api/branches'
    | '/api/contact'
    | '/api/documents'
    | '/api/news'
    | '/api/notifications'
    | '/api/school'
    | '/api/site-settings'
    | '/api/student'
    | '/api/students'
    | '/api/teacher'
    | '/api/teachers'
    | '/api/teaching-assignments'
    | '/api/users'
    | '/app/academic'
    | '/app/accountant'
    | '/app/admin'
    | '/app/registrar'
    | '/app/staff'
    | '/app/student'
    | '/app/supervisor'
    | '/app/teacher'
    | '/media/$file'
    | '/api/academic/assessment-types'
    | '/api/academic/assessments'
    | '/api/academic/attendance'
    | '/api/academic/classes'
    | '/api/academic/exam-sessions'
    | '/api/academic/grades'
    | '/api/academic/subjects'
    | '/api/academic/terms'
    | '/api/academic/warnings'
    | '/api/academic/years'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/branches/$id'
    | '/api/finance/expenses'
    | '/api/finance/fee-types'
    | '/api/finance/payments'
    | '/api/media/cover'
    | '/api/news/$id'
    | '/api/news/manage'
    | '/api/notifications/read'
    | '/api/notifications/sent'
    | '/api/students/$id'
    | '/api/students/me'
    | '/api/teachers/$id'
    | '/api/teaching-assignments/$id'
    | '/api/users/$id'
    | '/api/users/migrate'
    | '/api/academic/assessments/$id'
    | '/api/academic/attendance/$id'
    | '/api/academic/classes/$id'
    | '/api/academic/exam-sessions/$id'
    | '/api/academic/grades/$id'
    | '/api/academic/subjects/$id'
    | '/api/academic/terms/$id'
    | '/api/academic/warnings/$id'
    | '/api/academic/years/$id'
    | '/api/branches/$id/branch-head'
    | '/api/branches/$id/duties'
    | '/api/branches/$id/financial-officer'
    | '/api/branches/$id/members'
    | '/api/branches/$id/teachers'
    | '/api/documents/$id/archive'
    | '/api/documents/$id/download'
    | '/api/finance/expenses/$id'
    | '/api/finance/fee-types/$id'
    | '/api/finance/payments/$id'
    | '/api/students/$id/promote'
    | '/api/students/$id/transfer'
    | '/api/users/$id/reset-password'
    | '/api/academic/classes/$id/class-subjects'
    | '/api/academic/classes/$id/results'
    | '/api/academic/classes/$id/timetable'
    | '/api/academic/classes/$id/transfer'
    | '/api/branches/$id/duties/$responsibilityId'
    | '/api/academic/classes/$id/class-subjects/$subjectId'
    | '/api/academic/classes/$id/timetable/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/login'
    | '/welcome'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/news'
    | '/programs'
    | '/api/audit'
    | '/api/branches'
    | '/api/contact'
    | '/api/documents'
    | '/api/news'
    | '/api/notifications'
    | '/api/school'
    | '/api/site-settings'
    | '/api/student'
    | '/api/students'
    | '/api/teacher'
    | '/api/teachers'
    | '/api/teaching-assignments'
    | '/api/users'
    | '/app/academic'
    | '/app/accountant'
    | '/app/admin'
    | '/app/registrar'
    | '/app/staff'
    | '/app/student'
    | '/app/supervisor'
    | '/app/teacher'
    | '/media/$file'
    | '/'
    | '/api/academic/assessment-types'
    | '/api/academic/assessments'
    | '/api/academic/attendance'
    | '/api/academic/classes'
    | '/api/academic/exam-sessions'
    | '/api/academic/grades'
    | '/api/academic/subjects'
    | '/api/academic/terms'
    | '/api/academic/warnings'
    | '/api/academic/years'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/branches/$id'
    | '/api/finance/expenses'
    | '/api/finance/fee-types'
    | '/api/finance/payments'
    | '/api/media/cover'
    | '/api/news/$id'
    | '/api/news/manage'
    | '/api/notifications/read'
    | '/api/notifications/sent'
    | '/api/students/$id'
    | '/api/students/me'
    | '/api/teachers/$id'
    | '/api/teaching-assignments/$id'
    | '/api/users/$id'
    | '/api/users/migrate'
    | '/api/academic/assessments/$id'
    | '/api/academic/attendance/$id'
    | '/api/academic/classes/$id'
    | '/api/academic/exam-sessions/$id'
    | '/api/academic/grades/$id'
    | '/api/academic/subjects/$id'
    | '/api/academic/terms/$id'
    | '/api/academic/warnings/$id'
    | '/api/academic/years/$id'
    | '/api/branches/$id/branch-head'
    | '/api/branches/$id/duties'
    | '/api/branches/$id/financial-officer'
    | '/api/branches/$id/members'
    | '/api/branches/$id/teachers'
    | '/api/documents/$id/archive'
    | '/api/documents/$id/download'
    | '/api/finance/expenses/$id'
    | '/api/finance/fee-types/$id'
    | '/api/finance/payments/$id'
    | '/api/students/$id/promote'
    | '/api/students/$id/transfer'
    | '/api/users/$id/reset-password'
    | '/api/academic/classes/$id/class-subjects'
    | '/api/academic/classes/$id/results'
    | '/api/academic/classes/$id/timetable'
    | '/api/academic/classes/$id/transfer'
    | '/api/branches/$id/duties/$responsibilityId'
    | '/api/academic/classes/$id/class-subjects/$subjectId'
    | '/api/academic/classes/$id/timetable/$entryId'
  id:
    | '__root__'
    | '/_marketing'
    | '/app'
    | '/login'
    | '/welcome'
    | '/_marketing/about'
    | '/_marketing/admissions'
    | '/_marketing/contact'
    | '/_marketing/news'
    | '/_marketing/programs'
    | '/api/audit'
    | '/api/branches'
    | '/api/contact'
    | '/api/documents'
    | '/api/news'
    | '/api/notifications'
    | '/api/school'
    | '/api/site-settings'
    | '/api/student'
    | '/api/students'
    | '/api/teacher'
    | '/api/teachers'
    | '/api/teaching-assignments'
    | '/api/users'
    | '/app/academic'
    | '/app/accountant'
    | '/app/admin'
    | '/app/registrar'
    | '/app/staff'
    | '/app/student'
    | '/app/supervisor'
    | '/app/teacher'
    | '/media/$file'
    | '/_marketing/'
    | '/api/academic/assessment-types'
    | '/api/academic/assessments'
    | '/api/academic/attendance'
    | '/api/academic/classes'
    | '/api/academic/exam-sessions'
    | '/api/academic/grades'
    | '/api/academic/subjects'
    | '/api/academic/terms'
    | '/api/academic/warnings'
    | '/api/academic/years'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/branches/$id'
    | '/api/finance/expenses'
    | '/api/finance/fee-types'
    | '/api/finance/payments'
    | '/api/media/cover'
    | '/api/news/$id'
    | '/api/news/manage'
    | '/api/notifications/read'
    | '/api/notifications/sent'
    | '/api/students/$id'
    | '/api/students/me'
    | '/api/teachers/$id'
    | '/api/teaching-assignments/$id'
    | '/api/users/$id'
    | '/api/users/migrate'
    | '/api/academic/assessments/$id'
    | '/api/academic/attendance/$id'
    | '/api/academic/classes/$id'
    | '/api/academic/exam-sessions/$id'
    | '/api/academic/grades/$id'
    | '/api/academic/subjects/$id'
    | '/api/academic/terms/$id'
    | '/api/academic/warnings/$id'
    | '/api/academic/years/$id'
    | '/api/branches/$id/branch-head'
    | '/api/branches/$id/duties'
    | '/api/branches/$id/financial-officer'
    | '/api/branches/$id/members'
    | '/api/branches/$id/teachers'
    | '/api/documents/$id/archive'
    | '/api/documents/$id/download'
    | '/api/finance/expenses/$id'
    | '/api/finance/fee-types/$id'
    | '/api/finance/payments/$id'
    | '/api/students/$id/promote'
    | '/api/students/$id/transfer'
    | '/api/users/$id/reset-password'
    | '/api/academic/classes/$id/class-subjects'
    | '/api/academic/classes/$id/results'
    | '/api/academic/classes/$id/timetable'
    | '/api/academic/classes/$id/transfer'
    | '/api/branches/$id/duties/$responsibilityId'
    | '/api/academic/classes/$id/class-subjects/$subjectId'
    | '/api/academic/classes/$id/timetable/$entryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiAuditRoute: typeof ApiAuditRoute
  ApiBranchesRoute: typeof ApiBranchesRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
  ApiDocumentsRoute: typeof ApiDocumentsRouteWithChildren
  ApiNewsRoute: typeof ApiNewsRouteWithChildren
  ApiNotificationsRoute: typeof ApiNotificationsRouteWithChildren
  ApiSchoolRoute: typeof ApiSchoolRoute
  ApiSiteSettingsRoute: typeof ApiSiteSettingsRoute
  ApiStudentRoute: typeof ApiStudentRoute
  ApiStudentsRoute: typeof ApiStudentsRouteWithChildren
  ApiTeacherRoute: typeof ApiTeacherRoute
  ApiTeachersRoute: typeof ApiTeachersRouteWithChildren
  ApiTeachingAssignmentsRoute: typeof ApiTeachingAssignmentsRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  MediaFileRoute: typeof MediaFileRoute
  ApiAcademicAssessmentTypesRoute: typeof ApiAcademicAssessmentTypesRoute
  ApiAcademicAssessmentsRoute: typeof ApiAcademicAssessmentsRouteWithChildren
  ApiAcademicAttendanceRoute: typeof ApiAcademicAttendanceRouteWithChildren
  ApiAcademicClassesRoute: typeof ApiAcademicClassesRouteWithChildren
  ApiAcademicExamSessionsRoute: typeof ApiAcademicExamSessionsRouteWithChildren
  ApiAcademicGradesRoute: typeof ApiAcademicGradesRouteWithChildren
  ApiAcademicSubjectsRoute: typeof ApiAcademicSubjectsRouteWithChildren
  ApiAcademicTermsRoute: typeof ApiAcademicTermsRouteWithChildren
  ApiAcademicWarningsRoute: typeof ApiAcademicWarningsRouteWithChildren
  ApiAcademicYearsRoute: typeof ApiAcademicYearsRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiFinanceExpensesRoute: typeof ApiFinanceExpensesRouteWithChildren
  ApiFinanceFeeTypesRoute: typeof ApiFinanceFeeTypesRouteWithChildren
  ApiFinancePaymentsRoute: typeof ApiFinancePaymentsRouteWithChildren
  ApiMediaCoverRoute: typeof ApiMediaCoverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/admissions': {
      id: '/_marketing/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof MarketingAdmissionsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/news': {
      id: '/_marketing/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof MarketingNewsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/programs': {
      id: '/_marketing/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof MarketingProgramsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/audit': {
      id: '/api/audit'
      path: '/api/audit'
      fullPath: '/api/audit'
      preLoaderRoute: typeof ApiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/branches': {
      id: '/api/branches'
      path: '/api/branches'
      fullPath: '/api/branches'
      preLoaderRoute: typeof ApiBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/school': {
      id: '/api/school'
      path: '/api/school'
      fullPath: '/api/school'
      preLoaderRoute: typeof ApiSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-settings': {
      id: '/api/site-settings'
      path: '/api/site-settings'
      fullPath: '/api/site-settings'
      preLoaderRoute: typeof ApiSiteSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/student': {
      id: '/api/student'
      path: '/api/student'
      fullPath: '/api/student'
      preLoaderRoute: typeof ApiStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students': {
      id: '/api/students'
      path: '/api/students'
      fullPath: '/api/students'
      preLoaderRoute: typeof ApiStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teacher': {
      id: '/api/teacher'
      path: '/api/teacher'
      fullPath: '/api/teacher'
      preLoaderRoute: typeof ApiTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teachers': {
      id: '/api/teachers'
      path: '/api/teachers'
      fullPath: '/api/teachers'
      preLoaderRoute: typeof ApiTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teaching-assignments': {
      id: '/api/teaching-assignments'
      path: '/api/teaching-assignments'
      fullPath: '/api/teaching-assignments'
      preLoaderRoute: typeof ApiTeachingAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/academic': {
      id: '/app/academic'
      path: '/academic'
      fullPath: '/app/academic'
      preLoaderRoute: typeof AppAcademicRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accountant': {
      id: '/app/accountant'
      path: '/accountant'
      fullPath: '/app/accountant'
      preLoaderRoute: typeof AppAccountantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registrar': {
      id: '/app/registrar'
      path: '/registrar'
      fullPath: '/app/registrar'
      preLoaderRoute: typeof AppRegistrarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student': {
      id: '/app/student'
      path: '/student'
      fullPath: '/app/student'
      preLoaderRoute: typeof AppStudentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/supervisor': {
      id: '/app/supervisor'
      path: '/supervisor'
      fullPath: '/app/supervisor'
      preLoaderRoute: typeof AppSupervisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher': {
      id: '/app/teacher'
      path: '/teacher'
      fullPath: '/app/teacher'
      preLoaderRoute: typeof AppTeacherRouteImport
      parentRoute: typeof AppRoute
    }
    '/media/$file': {
      id: '/media/$file'
      path: '/media/$file'
      fullPath: '/media/$file'
      preLoaderRoute: typeof MediaFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academic/assessment-types': {
      id: '/api/academic/assessment-types'
      path: '/api/academic/assessment-types'
      fullPath: '/api/academic/assessment-types'
      preLoaderRoute: typeof ApiAcademicAssessmentTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academic/assessments': {
      id: '/api/academic/assessments'
      path: '/api/academic/assessments'
      fullPath: '/api/academic/assessments'
      preLoaderRoute: typeof ApiAcademicAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academic/attendance': {
      id: '/api/academic/attendance'
      path: '/api/academic/attendance'
      fullPath: '/api/academic/attendance'
      preLoaderRoute: typeof ApiAcademicAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academic/classes': {
      id: '/api/academic/classes'
      path: '/api/academic/classes'
      fullPath: '/api/academic/classes'
      preLoaderRoute: typeof ApiAcademicClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academic/exam-sessions': {
      id: '/api/academic/exam-sessions'
      path: '/api/academic/exam-sessions'
      fullPath: '/api/academic/exam-sessions'
      preLoaderRoute: typeof ApiAcademicExamSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academic/grades': {
      id: '/api/academic/grades'
      path: '/api/academic/grades'
      fullPath: '/api/academic/grades'
      preLoaderRoute: typeof ApiAcademicGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academic/subjects': {
      id: '/api/academic/subjects'
      path: '/api/academic/subjects'
      fullPath: '/api/academic/subjects'
      preLoaderRoute: typeof ApiAcademicSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academic/terms': {
      id: '/api/academic/terms'
      path: '/api/academic/terms'
      fullPath: '/api/academic/terms'
      preLoaderRoute: typeof ApiAcademicTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academic/warnings': {
      id: '/api/academic/warnings'
      path: '/api/academic/warnings'
      fullPath: '/api/academic/warnings'
      preLoaderRoute: typeof ApiAcademicWarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/academic/years': {
      id: '/api/academic/years'
      path: '/api/academic/years'
      fullPath: '/api/academic/years'
      preLoaderRoute: typeof ApiAcademicYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/branches/$id': {
      id: '/api/branches/$id'
      path: '/$id'
      fullPath: '/api/branches/$id'
      preLoaderRoute: typeof ApiBranchesIdRouteImport
      parentRoute: typeof ApiBranchesRoute
    }
    '/api/finance/expenses': {
      id: '/api/finance/expenses'
      path: '/api/finance/expenses'
      fullPath: '/api/finance/expenses'
      preLoaderRoute: typeof ApiFinanceExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/fee-types': {
      id: '/api/finance/fee-types'
      path: '/api/finance/fee-types'
      fullPath: '/api/finance/fee-types'
      preLoaderRoute: typeof ApiFinanceFeeTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/payments': {
      id: '/api/finance/payments'
      path: '/api/finance/payments'
      fullPath: '/api/finance/payments'
      preLoaderRoute: typeof ApiFinancePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/cover': {
      id: '/api/media/cover'
      path: '/api/media/cover'
      fullPath: '/api/media/cover'
      preLoaderRoute: typeof ApiMediaCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/$id': {
      id: '/api/news/$id'
      path: '/$id'
      fullPath: '/api/news/$id'
      preLoaderRoute: typeof ApiNewsIdRouteImport
      parentRoute: typeof ApiNewsRoute
    }
    '/api/news/manage': {
      id: '/api/news/manage'
      path: '/manage'
      fullPath: '/api/news/manage'
      preLoaderRoute: typeof ApiNewsManageRouteImport
      parentRoute: typeof ApiNewsRoute
    }
    '/api/notifications/read': {
      id: '/api/notifications/read'
      path: '/read'
      fullPath: '/api/notifications/read'
      preLoaderRoute: typeof ApiNotificationsReadRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/notifications/sent': {
      id: '/api/notifications/sent'
      path: '/sent'
      fullPath: '/api/notifications/sent'
      preLoaderRoute: typeof ApiNotificationsSentRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/students/$id': {
      id: '/api/students/$id'
      path: '/$id'
      fullPath: '/api/students/$id'
      preLoaderRoute: typeof ApiStudentsIdRouteImport
      parentRoute: typeof ApiStudentsRoute
    }
    '/api/students/me': {
      id: '/api/students/me'
      path: '/me'
      fullPath: '/api/students/me'
      preLoaderRoute: typeof ApiStudentsMeRouteImport
      parentRoute: typeof ApiStudentsRoute
    }
    '/api/teachers/$id': {
      id: '/api/teachers/$id'
      path: '/$id'
      fullPath: '/api/teachers/$id'
      preLoaderRoute: typeof ApiTeachersIdRouteImport
      parentRoute: typeof ApiTeachersRoute
    }
    '/api/teaching-assignments/$id': {
      id: '/api/teaching-assignments/$id'
      path: '/$id'
      fullPath: '/api/teaching-assignments/$id'
      preLoaderRoute: typeof ApiTeachingAssignmentsIdRouteImport
      parentRoute: typeof ApiTeachingAssignmentsRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/users/migrate': {
      id: '/api/users/migrate'
      path: '/migrate'
      fullPath: '/api/users/migrate'
      preLoaderRoute: typeof ApiUsersMigrateRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/academic/assessments/$id': {
      id: '/api/academic/assessments/$id'
      path: '/$id'
      fullPath: '/api/academic/assessments/$id'
      preLoaderRoute: typeof ApiAcademicAssessmentsIdRouteImport
      parentRoute: typeof ApiAcademicAssessmentsRoute
    }
    '/api/academic/attendance/$id': {
      id: '/api/academic/attendance/$id'
      path: '/$id'
      fullPath: '/api/academic/attendance/$id'
      preLoaderRoute: typeof ApiAcademicAttendanceIdRouteImport
      parentRoute: typeof ApiAcademicAttendanceRoute
    }
    '/api/academic/classes/$id': {
      id: '/api/academic/classes/$id'
      path: '/$id'
      fullPath: '/api/academic/classes/$id'
      preLoaderRoute: typeof ApiAcademicClassesIdRouteImport
      parentRoute: typeof ApiAcademicClassesRoute
    }
    '/api/academic/exam-sessions/$id': {
      id: '/api/academic/exam-sessions/$id'
      path: '/$id'
      fullPath: '/api/academic/exam-sessions/$id'
      preLoaderRoute: typeof ApiAcademicExamSessionsIdRouteImport
      parentRoute: typeof ApiAcademicExamSessionsRoute
    }
    '/api/academic/grades/$id': {
      id: '/api/academic/grades/$id'
      path: '/$id'
      fullPath: '/api/academic/grades/$id'
      preLoaderRoute: typeof ApiAcademicGradesIdRouteImport
      parentRoute: typeof ApiAcademicGradesRoute
    }
    '/api/academic/subjects/$id': {
      id: '/api/academic/subjects/$id'
      path: '/$id'
      fullPath: '/api/academic/subjects/$id'
      preLoaderRoute: typeof ApiAcademicSubjectsIdRouteImport
      parentRoute: typeof ApiAcademicSubjectsRoute
    }
    '/api/academic/terms/$id': {
      id: '/api/academic/terms/$id'
      path: '/$id'
      fullPath: '/api/academic/terms/$id'
      preLoaderRoute: typeof ApiAcademicTermsIdRouteImport
      parentRoute: typeof ApiAcademicTermsRoute
    }
    '/api/academic/warnings/$id': {
      id: '/api/academic/warnings/$id'
      path: '/$id'
      fullPath: '/api/academic/warnings/$id'
      preLoaderRoute: typeof ApiAcademicWarningsIdRouteImport
      parentRoute: typeof ApiAcademicWarningsRoute
    }
    '/api/academic/years/$id': {
      id: '/api/academic/years/$id'
      path: '/$id'
      fullPath: '/api/academic/years/$id'
      preLoaderRoute: typeof ApiAcademicYearsIdRouteImport
      parentRoute: typeof ApiAcademicYearsRoute
    }
    '/api/branches/$id/branch-head': {
      id: '/api/branches/$id/branch-head'
      path: '/branch-head'
      fullPath: '/api/branches/$id/branch-head'
      preLoaderRoute: typeof ApiBranchesIdBranchHeadRouteImport
      parentRoute: typeof ApiBranchesIdRoute
    }
    '/api/branches/$id/duties': {
      id: '/api/branches/$id/duties'
      path: '/duties'
      fullPath: '/api/branches/$id/duties'
      preLoaderRoute: typeof ApiBranchesIdDutiesRouteImport
      parentRoute: typeof ApiBranchesIdRoute
    }
    '/api/branches/$id/financial-officer': {
      id: '/api/branches/$id/financial-officer'
      path: '/financial-officer'
      fullPath: '/api/branches/$id/financial-officer'
      preLoaderRoute: typeof ApiBranchesIdFinancialOfficerRouteImport
      parentRoute: typeof ApiBranchesIdRoute
    }
    '/api/branches/$id/members': {
      id: '/api/branches/$id/members'
      path: '/members'
      fullPath: '/api/branches/$id/members'
      preLoaderRoute: typeof ApiBranchesIdMembersRouteImport
      parentRoute: typeof ApiBranchesIdRoute
    }
    '/api/branches/$id/teachers': {
      id: '/api/branches/$id/teachers'
      path: '/teachers'
      fullPath: '/api/branches/$id/teachers'
      preLoaderRoute: typeof ApiBranchesIdTeachersRouteImport
      parentRoute: typeof ApiBranchesIdRoute
    }
    '/api/documents/$id/archive': {
      id: '/api/documents/$id/archive'
      path: '/$id/archive'
      fullPath: '/api/documents/$id/archive'
      preLoaderRoute: typeof ApiDocumentsIdArchiveRouteImport
      parentRoute: typeof ApiDocumentsRoute
    }
    '/api/documents/$id/download': {
      id: '/api/documents/$id/download'
      path: '/$id/download'
      fullPath: '/api/documents/$id/download'
      preLoaderRoute: typeof ApiDocumentsIdDownloadRouteImport
      parentRoute: typeof ApiDocumentsRoute
    }
    '/api/finance/expenses/$id': {
      id: '/api/finance/expenses/$id'
      path: '/$id'
      fullPath: '/api/finance/expenses/$id'
      preLoaderRoute: typeof ApiFinanceExpensesIdRouteImport
      parentRoute: typeof ApiFinanceExpensesRoute
    }
    '/api/finance/fee-types/$id': {
      id: '/api/finance/fee-types/$id'
      path: '/$id'
      fullPath: '/api/finance/fee-types/$id'
      preLoaderRoute: typeof ApiFinanceFeeTypesIdRouteImport
      parentRoute: typeof ApiFinanceFeeTypesRoute
    }
    '/api/finance/payments/$id': {
      id: '/api/finance/payments/$id'
      path: '/$id'
      fullPath: '/api/finance/payments/$id'
      preLoaderRoute: typeof ApiFinancePaymentsIdRouteImport
      parentRoute: typeof ApiFinancePaymentsRoute
    }
    '/api/students/$id/promote': {
      id: '/api/students/$id/promote'
      path: '/promote'
      fullPath: '/api/students/$id/promote'
      preLoaderRoute: typeof ApiStudentsIdPromoteRouteImport
      parentRoute: typeof ApiStudentsIdRoute
    }
    '/api/students/$id/transfer': {
      id: '/api/students/$id/transfer'
      path: '/transfer'
      fullPath: '/api/students/$id/transfer'
      preLoaderRoute: typeof ApiStudentsIdTransferRouteImport
      parentRoute: typeof ApiStudentsIdRoute
    }
    '/api/users/$id/reset-password': {
      id: '/api/users/$id/reset-password'
      path: '/reset-password'
      fullPath: '/api/users/$id/reset-password'
      preLoaderRoute: typeof ApiUsersIdResetPasswordRouteImport
      parentRoute: typeof ApiUsersIdRoute
    }
    '/api/academic/classes/$id/class-subjects': {
      id: '/api/academic/classes/$id/class-subjects'
      path: '/class-subjects'
      fullPath: '/api/academic/classes/$id/class-subjects'
      preLoaderRoute: typeof ApiAcademicClassesIdClassSubjectsRouteImport
      parentRoute: typeof ApiAcademicClassesIdRoute
    }
    '/api/academic/classes/$id/results': {
      id: '/api/academic/classes/$id/results'
      path: '/results'
      fullPath: '/api/academic/classes/$id/results'
      preLoaderRoute: typeof ApiAcademicClassesIdResultsRouteImport
      parentRoute: typeof ApiAcademicClassesIdRoute
    }
    '/api/academic/classes/$id/timetable': {
      id: '/api/academic/classes/$id/timetable'
      path: '/timetable'
      fullPath: '/api/academic/classes/$id/timetable'
      preLoaderRoute: typeof ApiAcademicClassesIdTimetableRouteImport
      parentRoute: typeof ApiAcademicClassesIdRoute
    }
    '/api/academic/classes/$id/transfer': {
      id: '/api/academic/classes/$id/transfer'
      path: '/transfer'
      fullPath: '/api/academic/classes/$id/transfer'
      preLoaderRoute: typeof ApiAcademicClassesIdTransferRouteImport
      parentRoute: typeof ApiAcademicClassesIdRoute
    }
    '/api/branches/$id/duties/$responsibilityId': {
      id: '/api/branches/$id/duties/$responsibilityId'
      path: '/$responsibilityId'
      fullPath: '/api/branches/$id/duties/$responsibilityId'
      preLoaderRoute: typeof ApiBranchesIdDutiesResponsibilityIdRouteImport
      parentRoute: typeof ApiBranchesIdDutiesRoute
    }
    '/api/academic/classes/$id/class-subjects/$subjectId': {
      id: '/api/academic/classes/$id/class-subjects/$subjectId'
      path: '/$subjectId'
      fullPath: '/api/academic/classes/$id/class-subjects/$subjectId'
      preLoaderRoute: typeof ApiAcademicClassesIdClassSubjectsSubjectIdRouteImport
      parentRoute: typeof ApiAcademicClassesIdClassSubjectsRoute
    }
    '/api/academic/classes/$id/timetable/$entryId': {
      id: '/api/academic/classes/$id/timetable/$entryId'
      path: '/$entryId'
      fullPath: '/api/academic/classes/$id/timetable/$entryId'
      preLoaderRoute: typeof ApiAcademicClassesIdTimetableEntryIdRouteImport
      parentRoute: typeof ApiAcademicClassesIdTimetableRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingAdmissionsRoute: typeof MarketingAdmissionsRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingNewsRoute: typeof MarketingNewsRoute
  MarketingProgramsRoute: typeof MarketingProgramsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingAdmissionsRoute: MarketingAdmissionsRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingNewsRoute: MarketingNewsRoute,
  MarketingProgramsRoute: MarketingProgramsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AppRouteChildren {
  AppAcademicRoute: typeof AppAcademicRoute
  AppAccountantRoute: typeof AppAccountantRoute
  AppAdminRoute: typeof AppAdminRoute
  AppRegistrarRoute: typeof AppRegistrarRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStudentRoute: typeof AppStudentRoute
  AppSupervisorRoute: typeof AppSupervisorRoute
  AppTeacherRoute: typeof AppTeacherRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicRoute: AppAcademicRoute,
  AppAccountantRoute: AppAccountantRoute,
  AppAdminRoute: AppAdminRoute,
  AppRegistrarRoute: AppRegistrarRoute,
  AppStaffRoute: AppStaffRoute,
  AppStudentRoute: AppStudentRoute,
  AppSupervisorRoute: AppSupervisorRoute,
  AppTeacherRoute: AppTeacherRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiBranchesIdDutiesRouteChildren {
  ApiBranchesIdDutiesResponsibilityIdRoute: typeof ApiBranchesIdDutiesResponsibilityIdRoute
}

const ApiBranchesIdDutiesRouteChildren: ApiBranchesIdDutiesRouteChildren = {
  ApiBranchesIdDutiesResponsibilityIdRoute:
    ApiBranchesIdDutiesResponsibilityIdRoute,
}

const ApiBranchesIdDutiesRouteWithChildren =
  ApiBranchesIdDutiesRoute._addFileChildren(ApiBranchesIdDutiesRouteChildren)

interface ApiBranchesIdRouteChildren {
  ApiBranchesIdBranchHeadRoute: typeof ApiBranchesIdBranchHeadRoute
  ApiBranchesIdDutiesRoute: typeof ApiBranchesIdDutiesRouteWithChildren
  ApiBranchesIdFinancialOfficerRoute: typeof ApiBranchesIdFinancialOfficerRoute
  ApiBranchesIdMembersRoute: typeof ApiBranchesIdMembersRoute
  ApiBranchesIdTeachersRoute: typeof ApiBranchesIdTeachersRoute
}

const ApiBranchesIdRouteChildren: ApiBranchesIdRouteChildren = {
  ApiBranchesIdBranchHeadRoute: ApiBranchesIdBranchHeadRoute,
  ApiBranchesIdDutiesRoute: ApiBranchesIdDutiesRouteWithChildren,
  ApiBranchesIdFinancialOfficerRoute: ApiBranchesIdFinancialOfficerRoute,
  ApiBranchesIdMembersRoute: ApiBranchesIdMembersRoute,
  ApiBranchesIdTeachersRoute: ApiBranchesIdTeachersRoute,
}

const ApiBranchesIdRouteWithChildren = ApiBranchesIdRoute._addFileChildren(
  ApiBranchesIdRouteChildren,
)

interface ApiBranchesRouteChildren {
  ApiBranchesIdRoute: typeof ApiBranchesIdRouteWithChildren
}

const ApiBranchesRouteChildren: ApiBranchesRouteChildren = {
  ApiBranchesIdRoute: ApiBranchesIdRouteWithChildren,
}

const ApiBranchesRouteWithChildren = ApiBranchesRoute._addFileChildren(
  ApiBranchesRouteChildren,
)

interface ApiDocumentsRouteChildren {
  ApiDocumentsIdArchiveRoute: typeof ApiDocumentsIdArchiveRoute
  ApiDocumentsIdDownloadRoute: typeof ApiDocumentsIdDownloadRoute
}

const ApiDocumentsRouteChildren: ApiDocumentsRouteChildren = {
  ApiDocumentsIdArchiveRoute: ApiDocumentsIdArchiveRoute,
  ApiDocumentsIdDownloadRoute: ApiDocumentsIdDownloadRoute,
}

const ApiDocumentsRouteWithChildren = ApiDocumentsRoute._addFileChildren(
  ApiDocumentsRouteChildren,
)

interface ApiNewsRouteChildren {
  ApiNewsIdRoute: typeof ApiNewsIdRoute
  ApiNewsManageRoute: typeof ApiNewsManageRoute
}

const ApiNewsRouteChildren: ApiNewsRouteChildren = {
  ApiNewsIdRoute: ApiNewsIdRoute,
  ApiNewsManageRoute: ApiNewsManageRoute,
}

const ApiNewsRouteWithChildren =
  ApiNewsRoute._addFileChildren(ApiNewsRouteChildren)

interface ApiNotificationsRouteChildren {
  ApiNotificationsReadRoute: typeof ApiNotificationsReadRoute
  ApiNotificationsSentRoute: typeof ApiNotificationsSentRoute
}

const ApiNotificationsRouteChildren: ApiNotificationsRouteChildren = {
  ApiNotificationsReadRoute: ApiNotificationsReadRoute,
  ApiNotificationsSentRoute: ApiNotificationsSentRoute,
}

const ApiNotificationsRouteWithChildren =
  ApiNotificationsRoute._addFileChildren(ApiNotificationsRouteChildren)

interface ApiStudentsIdRouteChildren {
  ApiStudentsIdPromoteRoute: typeof ApiStudentsIdPromoteRoute
  ApiStudentsIdTransferRoute: typeof ApiStudentsIdTransferRoute
}

const ApiStudentsIdRouteChildren: ApiStudentsIdRouteChildren = {
  ApiStudentsIdPromoteRoute: ApiStudentsIdPromoteRoute,
  ApiStudentsIdTransferRoute: ApiStudentsIdTransferRoute,
}

const ApiStudentsIdRouteWithChildren = ApiStudentsIdRoute._addFileChildren(
  ApiStudentsIdRouteChildren,
)

interface ApiStudentsRouteChildren {
  ApiStudentsIdRoute: typeof ApiStudentsIdRouteWithChildren
  ApiStudentsMeRoute: typeof ApiStudentsMeRoute
}

const ApiStudentsRouteChildren: ApiStudentsRouteChildren = {
  ApiStudentsIdRoute: ApiStudentsIdRouteWithChildren,
  ApiStudentsMeRoute: ApiStudentsMeRoute,
}

const ApiStudentsRouteWithChildren = ApiStudentsRoute._addFileChildren(
  ApiStudentsRouteChildren,
)

interface ApiTeachersRouteChildren {
  ApiTeachersIdRoute: typeof ApiTeachersIdRoute
}

const ApiTeachersRouteChildren: ApiTeachersRouteChildren = {
  ApiTeachersIdRoute: ApiTeachersIdRoute,
}

const ApiTeachersRouteWithChildren = ApiTeachersRoute._addFileChildren(
  ApiTeachersRouteChildren,
)

interface ApiTeachingAssignmentsRouteChildren {
  ApiTeachingAssignmentsIdRoute: typeof ApiTeachingAssignmentsIdRoute
}

const ApiTeachingAssignmentsRouteChildren: ApiTeachingAssignmentsRouteChildren =
  {
    ApiTeachingAssignmentsIdRoute: ApiTeachingAssignmentsIdRoute,
  }

const ApiTeachingAssignmentsRouteWithChildren =
  ApiTeachingAssignmentsRoute._addFileChildren(
    ApiTeachingAssignmentsRouteChildren,
  )

interface ApiUsersIdRouteChildren {
  ApiUsersIdResetPasswordRoute: typeof ApiUsersIdResetPasswordRoute
}

const ApiUsersIdRouteChildren: ApiUsersIdRouteChildren = {
  ApiUsersIdResetPasswordRoute: ApiUsersIdResetPasswordRoute,
}

const ApiUsersIdRouteWithChildren = ApiUsersIdRoute._addFileChildren(
  ApiUsersIdRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRouteWithChildren
  ApiUsersMigrateRoute: typeof ApiUsersMigrateRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRouteWithChildren,
  ApiUsersMigrateRoute: ApiUsersMigrateRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiAcademicAssessmentsRouteChildren {
  ApiAcademicAssessmentsIdRoute: typeof ApiAcademicAssessmentsIdRoute
}

const ApiAcademicAssessmentsRouteChildren: ApiAcademicAssessmentsRouteChildren =
  {
    ApiAcademicAssessmentsIdRoute: ApiAcademicAssessmentsIdRoute,
  }

const ApiAcademicAssessmentsRouteWithChildren =
  ApiAcademicAssessmentsRoute._addFileChildren(
    ApiAcademicAssessmentsRouteChildren,
  )

interface ApiAcademicAttendanceRouteChildren {
  ApiAcademicAttendanceIdRoute: typeof ApiAcademicAttendanceIdRoute
}

const ApiAcademicAttendanceRouteChildren: ApiAcademicAttendanceRouteChildren = {
  ApiAcademicAttendanceIdRoute: ApiAcademicAttendanceIdRoute,
}

const ApiAcademicAttendanceRouteWithChildren =
  ApiAcademicAttendanceRoute._addFileChildren(
    ApiAcademicAttendanceRouteChildren,
  )

interface ApiAcademicClassesIdClassSubjectsRouteChildren {
  ApiAcademicClassesIdClassSubjectsSubjectIdRoute: typeof ApiAcademicClassesIdClassSubjectsSubjectIdRoute
}

const ApiAcademicClassesIdClassSubjectsRouteChildren: ApiAcademicClassesIdClassSubjectsRouteChildren =
  {
    ApiAcademicClassesIdClassSubjectsSubjectIdRoute:
      ApiAcademicClassesIdClassSubjectsSubjectIdRoute,
  }

const ApiAcademicClassesIdClassSubjectsRouteWithChildren =
  ApiAcademicClassesIdClassSubjectsRoute._addFileChildren(
    ApiAcademicClassesIdClassSubjectsRouteChildren,
  )

interface ApiAcademicClassesIdTimetableRouteChildren {
  ApiAcademicClassesIdTimetableEntryIdRoute: typeof ApiAcademicClassesIdTimetableEntryIdRoute
}

const ApiAcademicClassesIdTimetableRouteChildren: ApiAcademicClassesIdTimetableRouteChildren =
  {
    ApiAcademicClassesIdTimetableEntryIdRoute:
      ApiAcademicClassesIdTimetableEntryIdRoute,
  }

const ApiAcademicClassesIdTimetableRouteWithChildren =
  ApiAcademicClassesIdTimetableRoute._addFileChildren(
    ApiAcademicClassesIdTimetableRouteChildren,
  )

interface ApiAcademicClassesIdRouteChildren {
  ApiAcademicClassesIdClassSubjectsRoute: typeof ApiAcademicClassesIdClassSubjectsRouteWithChildren
  ApiAcademicClassesIdResultsRoute: typeof ApiAcademicClassesIdResultsRoute
  ApiAcademicClassesIdTimetableRoute: typeof ApiAcademicClassesIdTimetableRouteWithChildren
  ApiAcademicClassesIdTransferRoute: typeof ApiAcademicClassesIdTransferRoute
}

const ApiAcademicClassesIdRouteChildren: ApiAcademicClassesIdRouteChildren = {
  ApiAcademicClassesIdClassSubjectsRoute:
    ApiAcademicClassesIdClassSubjectsRouteWithChildren,
  ApiAcademicClassesIdResultsRoute: ApiAcademicClassesIdResultsRoute,
  ApiAcademicClassesIdTimetableRoute:
    ApiAcademicClassesIdTimetableRouteWithChildren,
  ApiAcademicClassesIdTransferRoute: ApiAcademicClassesIdTransferRoute,
}

const ApiAcademicClassesIdRouteWithChildren =
  ApiAcademicClassesIdRoute._addFileChildren(ApiAcademicClassesIdRouteChildren)

interface ApiAcademicClassesRouteChildren {
  ApiAcademicClassesIdRoute: typeof ApiAcademicClassesIdRouteWithChildren
}

const ApiAcademicClassesRouteChildren: ApiAcademicClassesRouteChildren = {
  ApiAcademicClassesIdRoute: ApiAcademicClassesIdRouteWithChildren,
}

const ApiAcademicClassesRouteWithChildren =
  ApiAcademicClassesRoute._addFileChildren(ApiAcademicClassesRouteChildren)

interface ApiAcademicExamSessionsRouteChildren {
  ApiAcademicExamSessionsIdRoute: typeof ApiAcademicExamSessionsIdRoute
}

const ApiAcademicExamSessionsRouteChildren: ApiAcademicExamSessionsRouteChildren =
  {
    ApiAcademicExamSessionsIdRoute: ApiAcademicExamSessionsIdRoute,
  }

const ApiAcademicExamSessionsRouteWithChildren =
  ApiAcademicExamSessionsRoute._addFileChildren(
    ApiAcademicExamSessionsRouteChildren,
  )

interface ApiAcademicGradesRouteChildren {
  ApiAcademicGradesIdRoute: typeof ApiAcademicGradesIdRoute
}

const ApiAcademicGradesRouteChildren: ApiAcademicGradesRouteChildren = {
  ApiAcademicGradesIdRoute: ApiAcademicGradesIdRoute,
}

const ApiAcademicGradesRouteWithChildren =
  ApiAcademicGradesRoute._addFileChildren(ApiAcademicGradesRouteChildren)

interface ApiAcademicSubjectsRouteChildren {
  ApiAcademicSubjectsIdRoute: typeof ApiAcademicSubjectsIdRoute
}

const ApiAcademicSubjectsRouteChildren: ApiAcademicSubjectsRouteChildren = {
  ApiAcademicSubjectsIdRoute: ApiAcademicSubjectsIdRoute,
}

const ApiAcademicSubjectsRouteWithChildren =
  ApiAcademicSubjectsRoute._addFileChildren(ApiAcademicSubjectsRouteChildren)

interface ApiAcademicTermsRouteChildren {
  ApiAcademicTermsIdRoute: typeof ApiAcademicTermsIdRoute
}

const ApiAcademicTermsRouteChildren: ApiAcademicTermsRouteChildren = {
  ApiAcademicTermsIdRoute: ApiAcademicTermsIdRoute,
}

const ApiAcademicTermsRouteWithChildren =
  ApiAcademicTermsRoute._addFileChildren(ApiAcademicTermsRouteChildren)

interface ApiAcademicWarningsRouteChildren {
  ApiAcademicWarningsIdRoute: typeof ApiAcademicWarningsIdRoute
}

const ApiAcademicWarningsRouteChildren: ApiAcademicWarningsRouteChildren = {
  ApiAcademicWarningsIdRoute: ApiAcademicWarningsIdRoute,
}

const ApiAcademicWarningsRouteWithChildren =
  ApiAcademicWarningsRoute._addFileChildren(ApiAcademicWarningsRouteChildren)

interface ApiAcademicYearsRouteChildren {
  ApiAcademicYearsIdRoute: typeof ApiAcademicYearsIdRoute
}

const ApiAcademicYearsRouteChildren: ApiAcademicYearsRouteChildren = {
  ApiAcademicYearsIdRoute: ApiAcademicYearsIdRoute,
}

const ApiAcademicYearsRouteWithChildren =
  ApiAcademicYearsRoute._addFileChildren(ApiAcademicYearsRouteChildren)

interface ApiFinanceExpensesRouteChildren {
  ApiFinanceExpensesIdRoute: typeof ApiFinanceExpensesIdRoute
}

const ApiFinanceExpensesRouteChildren: ApiFinanceExpensesRouteChildren = {
  ApiFinanceExpensesIdRoute: ApiFinanceExpensesIdRoute,
}

const ApiFinanceExpensesRouteWithChildren =
  ApiFinanceExpensesRoute._addFileChildren(ApiFinanceExpensesRouteChildren)

interface ApiFinanceFeeTypesRouteChildren {
  ApiFinanceFeeTypesIdRoute: typeof ApiFinanceFeeTypesIdRoute
}

const ApiFinanceFeeTypesRouteChildren: ApiFinanceFeeTypesRouteChildren = {
  ApiFinanceFeeTypesIdRoute: ApiFinanceFeeTypesIdRoute,
}

const ApiFinanceFeeTypesRouteWithChildren =
  ApiFinanceFeeTypesRoute._addFileChildren(ApiFinanceFeeTypesRouteChildren)

interface ApiFinancePaymentsRouteChildren {
  ApiFinancePaymentsIdRoute: typeof ApiFinancePaymentsIdRoute
}

const ApiFinancePaymentsRouteChildren: ApiFinancePaymentsRouteChildren = {
  ApiFinancePaymentsIdRoute: ApiFinancePaymentsIdRoute,
}

const ApiFinancePaymentsRouteWithChildren =
  ApiFinancePaymentsRoute._addFileChildren(ApiFinancePaymentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
  ApiAuditRoute: ApiAuditRoute,
  ApiBranchesRoute: ApiBranchesRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
  ApiDocumentsRoute: ApiDocumentsRouteWithChildren,
  ApiNewsRoute: ApiNewsRouteWithChildren,
  ApiNotificationsRoute: ApiNotificationsRouteWithChildren,
  ApiSchoolRoute: ApiSchoolRoute,
  ApiSiteSettingsRoute: ApiSiteSettingsRoute,
  ApiStudentRoute: ApiStudentRoute,
  ApiStudentsRoute: ApiStudentsRouteWithChildren,
  ApiTeacherRoute: ApiTeacherRoute,
  ApiTeachersRoute: ApiTeachersRouteWithChildren,
  ApiTeachingAssignmentsRoute: ApiTeachingAssignmentsRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  MediaFileRoute: MediaFileRoute,
  ApiAcademicAssessmentTypesRoute: ApiAcademicAssessmentTypesRoute,
  ApiAcademicAssessmentsRoute: ApiAcademicAssessmentsRouteWithChildren,
  ApiAcademicAttendanceRoute: ApiAcademicAttendanceRouteWithChildren,
  ApiAcademicClassesRoute: ApiAcademicClassesRouteWithChildren,
  ApiAcademicExamSessionsRoute: ApiAcademicExamSessionsRouteWithChildren,
  ApiAcademicGradesRoute: ApiAcademicGradesRouteWithChildren,
  ApiAcademicSubjectsRoute: ApiAcademicSubjectsRouteWithChildren,
  ApiAcademicTermsRoute: ApiAcademicTermsRouteWithChildren,
  ApiAcademicWarningsRoute: ApiAcademicWarningsRouteWithChildren,
  ApiAcademicYearsRoute: ApiAcademicYearsRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiFinanceExpensesRoute: ApiFinanceExpensesRouteWithChildren,
  ApiFinanceFeeTypesRoute: ApiFinanceFeeTypesRouteWithChildren,
  ApiFinancePaymentsRoute: ApiFinancePaymentsRouteWithChildren,
  ApiMediaCoverRoute: ApiMediaCoverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
